// Generated by Auto (Composer) - 2026-05-22
// Model: Composer
// Slideshow layout — width, height, x, y in pixels only
(function(global) {
    'use strict';

    var STORAGE_KEY = 'photoframe-slideshow-layout';
    var SAVED_EVENT = 'photoframe-layout-saved';
    var API_PATH = '/api/photos/display-settings';
    var UNIT_PIXELS = 'px';

    var DEFAULT_INTERVAL_SECONDS = 5;
    var MIN_INTERVAL_SECONDS = 1;
    var MAX_INTERVAL_SECONDS = 86400;

    var DEFAULTS = {
        width: 0,
        height: 0,
        x: 0,
        y: 0,
        intervalSeconds: DEFAULT_INTERVAL_SECONDS,
        showDisplayZone: false,
        unit: UNIT_PIXELS
    };

    var memoryCache = null;

    function trimString(str) {
        if (str === null || str === undefined) {
            return '';
        }
        return String(str).replace(/^\s+|\s+$/g, '');
    }

    function viewportWidth() {
        var w = global.innerWidth;
        if (!w && document.documentElement) {
            w = document.documentElement.clientWidth;
        }
        if (!w && document.body) {
            w = document.body.clientWidth;
        }
        if (!w && global.screen) {
            w = global.screen.width;
        }
        return w > 0 ? w : 800;
    }

    function viewportHeight() {
        var h = global.innerHeight;
        if (!h && document.documentElement) {
            h = document.documentElement.clientHeight;
        }
        if (!h && document.body) {
            h = document.body.clientHeight;
        }
        if (!h && global.screen) {
            h = global.screen.height;
        }
        return h > 0 ? h : 600;
    }

    function syncStageViewport(stageEl, centerCellEl) {
        var w = viewportWidth();
        var h = viewportHeight();
        if (document.documentElement && document.documentElement.style) {
            document.documentElement.style.height = h + 'px';
        }
        if (document.body && document.body.style) {
            document.body.style.width = w + 'px';
            document.body.style.height = h + 'px';
        }
        if (stageEl && stageEl.style) {
            stageEl.style.width = w + 'px';
            stageEl.style.height = h + 'px';
        }
        if (centerCellEl && centerCellEl.style) {
            centerCellEl.style.width = w + 'px';
            centerCellEl.style.height = h + 'px';
        }
        return { width: w, height: h };
    }

    function clampInterval(value, fallback) {
        var n = parseInt(value, 10);
        if (isNaN(n) || n < MIN_INTERVAL_SECONDS) {
            return fallback;
        }
        if (n > MAX_INTERVAL_SECONDS) {
            return MAX_INTERVAL_SECONDS;
        }
        return n;
    }

    function clampPixel(value, fallback, maxValue) {
        var n = parseFloat(value, 10);
        var cap = maxValue || 32000;
        if (isNaN(n)) {
            return fallback;
        }
        if (n < 0) {
            return 0;
        }
        if (n > cap) {
            return cap;
        }
        return Math.round(n);
    }

    function migratePercentToPx(settings) {
        var s = settings || {};
        var vw = viewportWidth();
        var vh = viewportHeight();
        return {
            width: s.width > 0 ? clampPixel(s.width / 100 * vw, 0, 32000) : 0,
            height: s.height > 0 ? clampPixel(s.height / 100 * vh, 0, 32000) : 0,
            x: clampPixel(s.x / 100 * vw, 0, 32000),
            y: clampPixel(s.y / 100 * vh, 0, 32000),
            unit: UNIT_PIXELS
        };
    }

    function normalize(settings) {
        var s = settings || {};
        var unit = trimString(s.unit);
        if (unit === '%' || unit === 'percent') {
            return migratePercentToPx(s);
        }
        return {
            width: clampPixel(s.width, DEFAULTS.width, 32000),
            height: clampPixel(s.height, DEFAULTS.height, 32000),
            x: clampPixel(s.x, DEFAULTS.x, 32000),
            y: clampPixel(s.y, DEFAULTS.y, 32000),
            intervalSeconds: clampInterval(s.intervalSeconds, DEFAULTS.intervalSeconds),
            showDisplayZone: !!s.showDisplayZone,
            unit: UNIT_PIXELS
        };
    }

    function resolve(settings) {
        var s = normalize(settings);
        var vw = viewportWidth();
        var vh = viewportHeight();
        return {
            width: s.width > 0 ? s.width : vw,
            height: s.height > 0 ? s.height : vh,
            x: s.x,
            y: s.y,
            unit: UNIT_PIXELS
        };
    }

    function readInputValue(inputEl) {
        var raw;
        if (!inputEl) {
            return '';
        }
        raw = trimString(inputEl.value);
        if (raw !== '') {
            return raw;
        }
        return '';
    }

    function readFromForm(widthEl, heightEl, xEl, yEl, intervalEl, showZoneEl) {
        var out = {
            width: readInputValue(widthEl),
            height: readInputValue(heightEl),
            x: readInputValue(xEl),
            y: readInputValue(yEl),
            intervalSeconds: readInputValue(intervalEl),
            unit: UNIT_PIXELS
        };
        if (showZoneEl) {
            out.showDisplayZone = !!showZoneEl.checked;
        }
        return out;
    }

    function parseNumberFromJson(text, field, fallback) {
        var re;
        var match;
        re = new RegExp('"' + field + '"\\s*:\\s*([0-9]+(?:\\.[0-9]+)?)');
        match = re.exec(text);
        if (match && match.length > 1) {
            return clampPixel(match[1], fallback, 32000);
        }
        return fallback;
    }

    function parseIntervalFromJson(text, fallback) {
        var re;
        var match;
        re = /"intervalSeconds"\s*:\s*([0-9]+)/;
        match = re.exec(text);
        if (match && match.length > 1) {
            return clampInterval(match[1], fallback);
        }
        return fallback;
    }

    function parseUnitFromJson(text) {
        var match = /"unit"\s*:\s*"([^"]+)"/.exec(text);
        if (match && match.length > 1) {
            return match[1];
        }
        return '';
    }

    function parseResponse(text) {
        var parsed;
        if (!text) {
            return normalize(DEFAULTS);
        }
        if (typeof JSON !== 'undefined' && JSON.parse) {
            try {
                parsed = JSON.parse(text);
                return normalize({
                    width: parsed.width,
                    height: parsed.height,
                    x: parsed.x,
                    y: parsed.y,
                    intervalSeconds: parsed.intervalSeconds,
                    showDisplayZone: parsed.showDisplayZone,
                    unit: parsed.unit
                });
            } catch (e1) {}
        }
        return normalize({
            width: parseNumberFromJson(text, 'width', DEFAULTS.width),
            height: parseNumberFromJson(text, 'height', DEFAULTS.height),
            x: parseNumberFromJson(text, 'x', DEFAULTS.x),
            y: parseNumberFromJson(text, 'y', DEFAULTS.y),
            intervalSeconds: parseIntervalFromJson(text, DEFAULTS.intervalSeconds),
            showDisplayZone: parseBooleanFromJson(text, 'showDisplayZone', DEFAULTS.showDisplayZone),
            unit: parseUnitFromJson(text)
        });
    }

    function parseBooleanFromJson(text, field, fallback) {
        var re;
        var match;
        re = new RegExp('"' + field + '"\\s*:\\s*(true|false)', 'i');
        match = re.exec(text);
        if (match && match.length > 1) {
            return match[1].toLowerCase() === 'true';
        }
        return fallback;
    }

    function stringifySettings(settings) {
        var s = normalize(settings);
        if (typeof JSON !== 'undefined' && JSON.stringify) {
            return JSON.stringify(s);
        }
        return '{"width":' + s.width + ',"height":' + s.height + ',"x":' + s.x
            + ',"y":' + s.y + ',"intervalSeconds":' + s.intervalSeconds
            + ',"showDisplayZone":' + (s.showDisplayZone ? 'true' : 'false')
            + ',"unit":"' + UNIT_PIXELS + '"}';
    }

    function saveLocal(settings) {
        var normalized = normalize(settings);
        memoryCache = normalized;
        try {
            if (global.localStorage) {
                global.localStorage.setItem(STORAGE_KEY, stringifySettings(normalized));
            }
        } catch (e2) {}
        return normalized;
    }

    function loadLocal() {
        var raw;
        if (memoryCache) {
            return normalize(memoryCache);
        }
        try {
            if (global.localStorage) {
                raw = global.localStorage.getItem(STORAGE_KEY);
                if (raw) {
                    memoryCache = parseResponse(raw);
                    return memoryCache;
                }
            }
        } catch (e3) {}
        return normalize(DEFAULTS);
    }

    function load(callback) {
        var xhr;
        if (!global.XMLHttpRequest) {
            callback(loadLocal());
            return;
        }
        xhr = new XMLHttpRequest();
        xhr.open('GET', API_PATH + '?_=' + new Date().getTime(), true);
        xhr.onreadystatechange = function() {
            if (xhr.readyState !== 4) {
                return;
            }
            if (xhr.status === 200) {
                callback(saveLocal(parseResponse(xhr.responseText)));
                return;
            }
            callback(loadLocal());
        };
        try {
            xhr.send(null);
        } catch (e4) {
            callback(loadLocal());
        }
    }

    function save(settings, callback) {
        var xhr;
        var normalized = saveLocal(settings);
        var done = function(ok, result) {
            if (typeof callback === 'function') {
                callback(ok, result || normalized);
            }
        };
        if (!global.XMLHttpRequest) {
            notifySaved();
            done(true, normalized);
            return;
        }
        xhr = new XMLHttpRequest();
        xhr.open('PUT', API_PATH, true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.onreadystatechange = function() {
            if (xhr.readyState !== 4) {
                return;
            }
            if (xhr.status === 200) {
                done(true, saveLocal(parseResponse(xhr.responseText)));
                notifySaved();
                return;
            }
            notifySaved();
            done(false, normalized);
        };
        try {
            xhr.send(stringifySettings(normalized));
        } catch (e5) {
            notifySaved();
            done(false, normalized);
        }
    }

    function notifySaved() {
        var ev;
        if (document.createEvent) {
            try {
                ev = document.createEvent('Event');
                ev.initEvent(SAVED_EVENT, true, true);
                global.dispatchEvent(ev);
            } catch (e1) {}
        }
    }

    function applyToFrame(frameEl, settings) {
        var s = resolve(settings);
        if (frameEl && frameEl.style) {
            frameEl.style.cssText = 'position:absolute;margin:0;padding:0;overflow:hidden;'
                + 'line-height:0;text-align:center;left:' + s.x + 'px;top:' + s.y + 'px;'
                + 'width:' + s.width + 'px;height:' + s.height + 'px;';
        }
        return s;
    }

    function applyDisplayZoneGuide(guideEl, settings, hideGuide) {
        var s;
        var normalized;
        if (!guideEl || !guideEl.style) {
            return null;
        }
        if (hideGuide) {
            guideEl.style.display = 'none';
            return null;
        }
        normalized = normalize(settings);
        if (!normalized.showDisplayZone) {
            guideEl.style.display = 'none';
            return null;
        }
        s = resolve(settings);
        guideEl.style.display = 'block';
        guideEl.style.position = 'absolute';
        guideEl.style.margin = '0';
        guideEl.style.padding = '0';
        guideEl.style.boxSizing = 'border-box';
        guideEl.style.pointerEvents = 'none';
        guideEl.style.zIndex = '3';
        guideEl.style.border = '1px solid #505050';
        guideEl.style.background = 'transparent';
        guideEl.style.left = s.x + 'px';
        guideEl.style.top = s.y + 'px';
        guideEl.style.width = s.width + 'px';
        guideEl.style.height = s.height + 'px';
        return s;
    }

    function getImageDimensions(photoEl, callback) {
        var w;
        var h;
        var tmp;
        if (!photoEl || typeof callback !== 'function') {
            return;
        }
        w = 0;
        h = 0;
        if (photoEl.naturalWidth) {
            w = photoEl.naturalWidth;
        } else if (photoEl.width) {
            w = photoEl.width;
        }
        if (photoEl.naturalHeight) {
            h = photoEl.naturalHeight;
        } else if (photoEl.height) {
            h = photoEl.height;
        }
        if (w > 0 && h > 0) {
            callback(w, h);
            return;
        }
        if (!photoEl.src) {
            callback(0, 0);
            return;
        }
        tmp = new Image();
        tmp.onload = function() {
            callback(tmp.width, tmp.height);
        };
        tmp.onerror = function() {
            callback(photoEl.width || 0, photoEl.height || 0);
        };
        tmp.src = photoEl.src;
    }

    function fitImageInFrame(photoEl, frameW, frameH, callback) {
        var scaleW;
        var scaleH;
        var scale;
        var w;
        var h;
        var marginLeft;
        var marginTop;

        function place(imgW, imgH) {
            if (!photoEl || !frameW || !frameH || !imgW || !imgH) {
                if (callback) {
                    callback(false);
                }
                return;
            }
            scaleW = frameW / imgW;
            scaleH = frameH / imgH;
            scale = scaleW < scaleH ? scaleW : scaleH;
            w = Math.round(imgW * scale);
            h = Math.round(imgH * scale);
            marginLeft = Math.round((frameW - w) / 2);
            marginTop = Math.round((frameH - h) / 2);
            if (marginLeft < 0) {
                marginLeft = 0;
            }
            if (marginTop < 0) {
                marginTop = 0;
            }
            photoEl.setAttribute('width', w);
            photoEl.setAttribute('height', h);
            photoEl.style.width = w + 'px';
            photoEl.style.height = h + 'px';
            photoEl.style.marginLeft = marginLeft + 'px';
            photoEl.style.marginTop = marginTop + 'px';
            if (callback) {
                callback(true);
            }
        }

        getImageDimensions(photoEl, place);
    }

    function bindSavedListener(handler) {
        if (global.addEventListener) {
            global.addEventListener(SAVED_EVENT, handler, false);
            global.addEventListener('storage', function(e) {
                if (e && e.key === STORAGE_KEY) {
                    handler();
                }
            }, false);
        } else if (global.attachEvent) {
            global.attachEvent('on' + SAVED_EVENT, handler);
        }
    }

    function getCached() {
        return memoryCache ? normalize(memoryCache) : loadLocal();
    }

    global.PhotoFrameLayout = {
        STORAGE_KEY: STORAGE_KEY,
        SAVED_EVENT: SAVED_EVENT,
        UNIT_PIXELS: UNIT_PIXELS,
        DEFAULTS: DEFAULTS,
        load: load,
        save: save,
        saveLocal: saveLocal,
        loadLocal: loadLocal,
        getCached: getCached,
        normalize: normalize,
        resolve: resolve,
        parseResponse: parseResponse,
        readFromForm: readFromForm,
        applyToFrame: applyToFrame,
        applyDisplayZoneGuide: applyDisplayZoneGuide,
        fitImageInFrame: fitImageInFrame,
        syncStageViewport: syncStageViewport,
        bindSavedListener: bindSavedListener,
        clampPixel: clampPixel,
        viewportWidth: viewportWidth,
        viewportHeight: viewportHeight
    };
}(typeof window !== 'undefined' ? window : this));
