// Generated by Auto (Composer) - 2026-05-25
// Model: Composer
package com.mwa.photoframe.controller;

import com.mwa.photoframe.api.PhotoApiResponse;
import com.mwa.photoframe.api.PhotoErrorCode;
import com.mwa.photoframe.api.PhotoFrameException;
import com.mwa.photoframe.util.PhotoFrameTraceLog;
import jakarta.servlet.http.HttpServletRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.io.IOException;

@RestControllerAdvice(basePackages = "com.mwa.photoframe.controller")
public class PhotoExceptionHandler {

    private static final Logger log = LoggerFactory.getLogger(PhotoExceptionHandler.class);

    @ExceptionHandler(PhotoFrameException.class)
    public Object handlePhotoFrameException(PhotoFrameException ex, HttpServletRequest request) {
        log.warn("API error {} {} code={} message={}",
                request.getMethod(),
                request.getRequestURI(),
                ex.getCode(),
                ex.getMessage());
        if (ex.getCause() != null) {
            log.debug("API error cause", ex.getCause());
        }
        String format = request.getParameter("format");
        return PhotoApiResponse.error(ex, format);
    }

    @ExceptionHandler(Exception.class)
    public Object handleException(Exception ex, HttpServletRequest request) {
        if (ex instanceof PhotoFrameException) {
            return handlePhotoFrameException((PhotoFrameException) ex, request);
        }
        Throwable cause = ex;
        while (cause != null) {
            if (cause instanceof PhotoFrameException) {
                return handlePhotoFrameException((PhotoFrameException) cause, request);
            }
            cause = cause.getCause();
        }
        String ioReason = ex instanceof IOException ? PhotoFrameTraceLog.classifyIo((IOException) ex) : null;
        String netReason = PhotoFrameTraceLog.classifyNetwork(ex);
        log.error("API unhandled {} {} ioReason={} netReason={} type={} message={}",
                request.getMethod(),
                request.getRequestURI(),
                ioReason,
                netReason,
                ex.getClass().getSimpleName(),
                ex.getMessage(),
                ex);
        PhotoFrameException wrapped = new PhotoFrameException(
                PhotoErrorCode.UNKNOWN,
                PhotoErrorCode.UNKNOWN.getDefaultMessage(),
                ex);
        return PhotoApiResponse.error(wrapped, request.getParameter("format"));
    }
}
