// Generated by Auto (Composer) - 2026-05-21
package com.mwa.photoframe.controller;

import com.mwa.photoframe.service.PhotoCatalogService;
import com.mwa.photoframe.service.SlideshowDisplaySettingsService;
import com.mwa.photoframe.source.HeicImageConverter;
import com.mwa.photoframe.source.PhotoEntry;
import com.mwa.photoframe.source.SlideshowDisplaySettings;
import javax.servlet.http.HttpServletRequest;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

@RestController
@RequestMapping("/api/photos")
public class PhotoController {

    private final PhotoCatalogService catalogService;
    private final SlideshowDisplaySettingsService displaySettingsService;

    public PhotoController(
            PhotoCatalogService catalogService,
            SlideshowDisplaySettingsService displaySettingsService) {
        this.catalogService = catalogService;
        this.displaySettingsService = displaySettingsService;
    }

    /**
     * Returns the next image URL. Plain text when format=text (legacy browsers).
     */
    @GetMapping("/next")
    public ResponseEntity<?> next(
            @RequestParam(required = false) String folder,
            @RequestParam(required = false, defaultValue = "json") String format,
            HttpServletRequest request) throws Exception {

        PhotoEntry entry = catalogService.nextPhoto(folder);
        String imageUrl = buildImageUrl(request, entry.getId(), folder);

        if ("text".equalsIgnoreCase(format) || "plain".equalsIgnoreCase(format)) {
            return ResponseEntity.ok()
                    .contentType(MediaType.TEXT_PLAIN)
                    .body(imageUrl);
        }

        Map<String, Object> body = new HashMap<>();
        body.put("success", true);
        body.put("id", entry.getId());
        body.put("url", imageUrl);
        body.put("mimeType", entry.getMimeType());
        return ResponseEntity.ok(body);
    }

    @GetMapping("/serve/{id}")
    public ResponseEntity<Resource> serve(
            @PathVariable String id,
            @RequestParam(required = false) String folder) throws Exception {

        catalogService.ensureCatalog(folder);
        PhotoEntry entry = catalogService.findById(id);
        if (entry == null) {
            return ResponseEntity.notFound().build();
        }
        Resource resource = catalogService.loadImageResource(entry);
        String mime = entry.getMimeType() != null ? entry.getMimeType() : MediaType.IMAGE_JPEG_VALUE;
        if (HeicImageConverter.isHeicMime(mime)
                || (entry.getLocalFileName() != null
                        && HeicImageConverter.isHeicPath(Paths.get(entry.getLocalFileName())))) {
            mime = MediaType.IMAGE_JPEG_VALUE;
        }
        return ResponseEntity.ok()
                .header(HttpHeaders.CACHE_CONTROL, "no-cache")
                .contentType(MediaType.parseMediaType(mime))
                .body(resource);
    }

    @GetMapping("/config")
    public ResponseEntity<Map<String, Object>> config() {
        Map<String, Object> body = new HashMap<>();
        body.put("defaultSource", catalogService.getDefaultSource());
        body.put("defaultTimerSeconds", catalogService.getDefaultTimerSeconds());
        return ResponseEntity.ok(body);
    }

    @GetMapping("/display-settings")
    public ResponseEntity<Map<String, Object>> getDisplaySettings() throws Exception {
        return ResponseEntity.ok(displaySettingsService.get().toMap());
    }

    @PutMapping("/display-settings")
    public ResponseEntity<Map<String, Object>> saveDisplaySettings(@RequestBody Map<String, Object> body)
            throws Exception {
        SlideshowDisplaySettings saved = displaySettingsService.save(
                SlideshowDisplaySettings.fromMap(body, catalogService.getDefaultTimerSeconds()));
        return ResponseEntity.ok(saved.toMap());
    }

    private String buildImageUrl(HttpServletRequest request, String id, String folder) {
        String base = request.getContextPath();
        StringBuilder url = new StringBuilder();
        url.append(base).append("/api/photos/serve/").append(id);
        boolean first = true;
        if (folder != null && !folder.isEmpty()) {
            url.append(first ? "?" : "&").append("folder=").append(folder);
        }
        url.append(first ? "?" : "&").append("_=").append(System.currentTimeMillis());
        return url.toString();
    }
}
