// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.controller;

import com.mwa.photoframe.api.PhotoApiResponse;
import com.mwa.photoframe.api.PhotoFrameException;
import javax.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

@RestControllerAdvice(basePackages = "com.mwa.photoframe.controller")
public class PhotoExceptionHandler {

    @ExceptionHandler(PhotoFrameException.class)
    public Object handlePhotoFrameException(PhotoFrameException ex, HttpServletRequest request) {
        String format = request.getParameter("format");
        return PhotoApiResponse.error(ex, format);
    }

    @ExceptionHandler(Exception.class)
    public Object handleException(Exception ex, HttpServletRequest request) {
        if (ex instanceof PhotoFrameException) {
            return handlePhotoFrameException((PhotoFrameException) ex, request);
        }
        Throwable cause = ex;
        while (cause != null) {
            if (cause instanceof PhotoFrameException) {
                return handlePhotoFrameException((PhotoFrameException) cause, request);
            }
            cause = cause.getCause();
        }
        PhotoFrameException wrapped = new PhotoFrameException(
                com.mwa.photoframe.api.PhotoErrorCode.UNKNOWN,
                com.mwa.photoframe.api.PhotoErrorCode.UNKNOWN.getDefaultMessage(),
                ex);
        return PhotoApiResponse.error(wrapped, request.getParameter("format"));
    }
}
