// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.controller;

import com.mwa.photoframe.api.PhotoErrorCode;
import com.mwa.photoframe.api.PhotoFrameException;
import com.mwa.photoframe.service.GooglePhotosPickerService;
import com.mwa.photoframe.service.PhotoCatalogService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.util.Map;

@RestController
@RequestMapping("/api/photos/google")
public class PhotoGoogleController {

    private final GooglePhotosPickerService pickerService;
    private final PhotoCatalogService catalogService;

    public PhotoGoogleController(GooglePhotosPickerService pickerService, PhotoCatalogService catalogService) {
        this.pickerService = pickerService;
        this.catalogService = catalogService;
    }

    @GetMapping("/status")
    public ResponseEntity<Map<String, Object>> status() throws Exception {
        try {
            return ResponseEntity.ok(pickerService.pickedStatus());
        } catch (IOException ex) {
            throw new PhotoFrameException(
                    PhotoErrorCode.AUTH_CONFIG,
                    PhotoErrorCode.AUTH_CONFIG.getDefaultMessage() + " " + ex.getMessage(),
                    ex);
        }
    }

    @GetMapping("/picked")
    public ResponseEntity<Map<String, Object>> listPicked() throws Exception {
        return ResponseEntity.ok(pickerService.listPicked());
    }

    @DeleteMapping("/picked/{id}")
    public ResponseEntity<Map<String, Object>> removePicked(@PathVariable String id) throws Exception {
        Map<String, Object> body = pickerService.removePicked(id);
        catalogService.invalidateCatalog();
        return ResponseEntity.ok(body);
    }

    @DeleteMapping("/picked")
    public ResponseEntity<Map<String, Object>> clearPicked() throws Exception {
        Map<String, Object> body = pickerService.clearPicked();
        catalogService.invalidateCatalog();
        return ResponseEntity.ok(body);
    }

    @PostMapping("/picker/session")
    public ResponseEntity<Map<String, Object>> createPickerSession() throws Exception {
        return ResponseEntity.ok(pickerService.createSession());
    }

    @GetMapping("/picker/session/{sessionId}")
    public ResponseEntity<Map<String, Object>> getPickerSession(@PathVariable String sessionId) throws Exception {
        return ResponseEntity.ok(pickerService.getSession(sessionId));
    }

    @PostMapping("/picker/session/{sessionId}/import")
    public ResponseEntity<Map<String, Object>> importPickerSession(@PathVariable String sessionId) throws Exception {
        Map<String, Object> body = pickerService.importSession(sessionId);
        catalogService.invalidateCatalog();
        return ResponseEntity.ok(body);
    }
}
