#!/bin/sh
# Generated by Auto (Composer) - 2026-05-30
# Model: Composer
set -eu

CRED_FILE="${PHOTOFRAME_GOOGLE_CREDENTIALS:-/app/google-photos-credentials.properties}"

if [ -n "${GOOGLE_PHOTOS_CLIENT_ID:-}" ] && [ -n "${GOOGLE_PHOTOS_CLIENT_SECRET:-}" ] && [ -n "${GOOGLE_PHOTOS_REFRESH_TOKEN:-}" ]; then
  umask 077
  cat > "$CRED_FILE" <<EOF
google.photos.client.id=${GOOGLE_PHOTOS_CLIENT_ID}
google.photos.client.secret=${GOOGLE_PHOTOS_CLIENT_SECRET}
google.photos.refresh.token=${GOOGLE_PHOTOS_REFRESH_TOKEN}
EOF
  echo "Wrote Google credentials from environment to ${CRED_FILE}"
fi

exec java -jar /app/photoframe.jar
