# Generated by Auto (Composer) - 2026-05-30
# Model: Composer
# Multi-stage build: storage-lib + PhotoFrame (Java 21).
# Build context must include ./storage-lib and ./backend + ./frontend (see .github/workflows/build-container.yml).

FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /build

# Install storage-lib into the local Maven repo
COPY storage-lib/pom.xml storage-lib/pom.xml
COPY storage-lib/storage-core storage-lib/storage-core
COPY storage-lib/storage-filesystem storage-lib/storage-filesystem
COPY storage-lib/storage-azure-blob storage-lib/storage-azure-blob
COPY storage-lib/storage-spring-boot-starter storage-lib/storage-spring-boot-starter
RUN cd storage-lib && mvn -q install -DskipTests

# PhotoFrame backend (frontend copied into JAR via maven-resources-plugin)
WORKDIR /build/backend
COPY backend/pom.xml .
RUN mvn -q dependency:go-offline -B

COPY backend/src ./src
COPY frontend ../frontend
RUN mvn -q clean package -DskipTests

FROM eclipse-temurin:21-jre-jammy

ARG GIT_TAG="unknown"
ENV GIT_TAG=${GIT_TAG}

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mkdir -p /app/data /app/logs

COPY --from=build /build/backend/target/photoframe.jar /app/photoframe.jar
COPY google-photos-credentials.properties.template /app/
COPY google-photos-picked.json.template /app/google-photos-picked.json
COPY slideshow-display.json.template /app/slideshow-display.json
COPY docker-entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

ENV PHOTOFRAME_HOME=/app
ENV SERVER_PORT=8082
ENV LOGGING_FILE_NAME=/app/logs/photoframe.log
ENV LOG_LEVEL=INFO
ENV PHOTOFRAME_STORAGE_PROVIDER=filesystem
ENV PHOTOFRAME_STORAGE_ROOT=/app/data
ENV PHOTOFRAME_GOOGLE_CREDENTIALS=/app/google-photos-credentials.properties
ENV PHOTOFRAME_GOOGLE_PICKED_FILE=/app/google-photos-picked.json
ENV PHOTOFRAME_DISPLAY_SETTINGS=/app/slideshow-display.json

EXPOSE 8082

HEALTHCHECK --interval=30s --timeout=5s --start-period=40s --retries=3 \
    CMD curl -f "http://127.0.0.1:${SERVER_PORT}/api/photos/config" || exit 1

ENTRYPOINT ["/app/docker-entrypoint.sh"]
