// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.api.client.googleapis.auth.oauth2.GoogleCredential;
import com.google.api.client.googleapis.json.GoogleJsonResponseException;
import com.google.api.client.http.ByteArrayContent;
import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.HttpResponseException;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.nio.charset.StandardCharsets;
import com.mwa.photoframe.api.GooglePickerApiErrors;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.mwa.photoframe.api.GooglePhotosApiErrors;
import com.mwa.photoframe.api.PhotoErrorCode;
import com.mwa.photoframe.api.PhotoFrameException;
import com.mwa.photoframe.api.PhotoApiResponse;
import com.mwa.photoframe.config.PhotoFrameConfig;
import com.mwa.photoframe.source.GooglePhotosClientFactory;
import com.mwa.photoframe.source.GooglePhotosCredentials;
import com.mwa.photoframe.source.GooglePhotosPickedStore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
public class GooglePhotosPickerService {

    private static final Logger log = LoggerFactory.getLogger(GooglePhotosPickerService.class);
    private static final String PICKER_BASE = "https://photospicker.googleapis.com/v1/";
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private final PhotoFrameConfig config;
    private final GooglePhotosService googlePhotosService;
    private final GooglePhotosImageCacheService imageCacheService;

    public GooglePhotosPickerService(
            PhotoFrameConfig config,
            GooglePhotosService googlePhotosService,
            GooglePhotosImageCacheService imageCacheService) {
        this.config = config;
        this.googlePhotosService = googlePhotosService;
        this.imageCacheService = imageCacheService;
    }

    public Map<String, Object> createSession() throws Exception {
        int existingCount = GooglePhotosPickedStore.count(resolvePickedPath());
        GoogleCredential credential = credential();
        NetHttpTransport transport = GoogleNetHttpTransport.newTrustedTransport();
        HttpResponse response;
        try {
            ObjectNode requestBody = MAPPER.createObjectNode();
            ObjectNode pickingConfig = requestBody.putObject("pickingConfig");
            pickingConfig.put("maxItemCount", "2000");
            String json = MAPPER.writeValueAsString(requestBody);
            ByteArrayContent content = new ByteArrayContent(
                    "application/json", json.getBytes(StandardCharsets.UTF_8));
            response = transport.createRequestFactory(credential)
                    .buildPostRequest(new GenericUrl(PICKER_BASE + "sessions"), content)
                    .execute();
        } catch (HttpResponseException ex) {
            throw GooglePickerApiErrors.toPhotoFrameException(ex);
        }
        JsonNode session = parseJson(response);
        String id = text(session, "id");
        String pickerUri = text(session, "pickerUri");
        if (id.isEmpty() || pickerUri.isEmpty()) {
            throw new PhotoFrameException(PhotoErrorCode.PICKER_SESSION_FAILED, "Picker session missing id or pickerUri.");
        }
        long pollMs = 3000;
        JsonNode polling = session.get("pollingConfig");
        if (polling != null) {
            pollMs = parseDurationMs(text(polling, "pollInterval"), 3000);
        }
        Map<String, Object> body = new HashMap<>();
        body.put("success", true);
        body.put("sessionId", id);
        body.put("pickerUri", pickerUri);
        body.put("pickerUriAutoclose", appendAutoclose(pickerUri));
        body.put("pollIntervalMs", pollMs);
        body.put("existingCount", existingCount);
        return body;
    }

    public Map<String, Object> getSession(String sessionId) throws Exception {
        GoogleCredential credential = credential();
        NetHttpTransport transport = GoogleNetHttpTransport.newTrustedTransport();
        HttpResponse response;
        try {
            response = transport.createRequestFactory(credential)
                    .buildGetRequest(new GenericUrl(PICKER_BASE + "sessions/" + sessionId))
                    .execute();
        } catch (HttpResponseException ex) {
            throw GooglePickerApiErrors.toPhotoFrameException(ex);
        }
        JsonNode session = parseJson(response);
        boolean mediaItemsSet = session.path("mediaItemsSet").asBoolean(false);
        long pollMs = 3000;
        JsonNode polling = session.get("pollingConfig");
        if (polling != null) {
            pollMs = parseDurationMs(text(polling, "pollInterval"), 3000);
        }
        Map<String, Object> body = new HashMap<>();
        body.put("success", true);
        body.put("sessionId", sessionId);
        body.put("mediaItemsSet", mediaItemsSet);
        body.put("pollIntervalMs", pollMs);
        return body;
    }

    public Map<String, Object> importSession(String sessionId) throws Exception {
        Map<String, Object> status = getSession(sessionId);
        if (!Boolean.TRUE.equals(status.get("mediaItemsSet"))) {
            throw new PhotoFrameException(
                    PhotoErrorCode.PICKER_NOT_READY,
                    "Selection not finished. Complete picking in Google Photos, then try again.");
        }
        PickedMediaBatch batch = listAllPickedMedia(sessionId);
        List<GooglePhotosPickedStore.StoredPickedItem> incoming = batch.photos;
        int skippedVideos = batch.skippedVideos;
        Path pickedPath = resolvePickedPath();
        int previousCount = GooglePhotosPickedStore.count(pickedPath);
        deleteSession(sessionId);

        if (incoming.isEmpty()) {
            if (previousCount == 0) {
                if (skippedVideos > 0) {
                    throw new PhotoFrameException(
                            PhotoErrorCode.NO_IMAGES,
                            "No photos were selected. " + skippedVideos
                                    + " video(s) were skipped (videos are not supported).");
                }
                throw new PhotoFrameException(
                        PhotoErrorCode.NO_IMAGES,
                        "No photos were selected. Choose at least one photo in Google Photos.");
            }
            Map<String, Object> body = new HashMap<>();
            body.put("success", true);
            body.put("added", 0);
            body.put("skippedVideos", skippedVideos);
            body.put("photoCount", previousCount);
            body.put("slideshowUrl", "/");
            body.put("message", "No new photos added. Total: " + previousCount + ".");
            return body;
        }

        int added = GooglePhotosPickedStore.merge(pickedPath, incoming);
        int total = GooglePhotosPickedStore.count(pickedPath);
        List<Map<String, Object>> toCache = buildToCacheList(incoming);
        log.info("Merged picker import: {} new, {} total, {} to cache, {} videos skipped at {}",
                added, total, toCache.size(), skippedVideos, pickedPath);
        Map<String, Object> body = new HashMap<>();
        body.put("success", true);
        body.put("added", added);
        body.put("imported", incoming.size());
        body.put("skippedVideos", skippedVideos);
        body.put("toCache", toCache);
        body.put("photoCount", total);
        body.put("slideshowUrl", "/");
        if (added > 0) {
            body.put("message", "Added " + added + " photo(s). Total: " + total + ".");
        } else {
            body.put("message", "Updated " + incoming.size() + " photo(s). Total: " + total + ".");
        }
        return body;
    }

    public Map<String, Object> cachePhoto(String id) throws Exception {
        GooglePhotosPickedStore.StoredPickedItem item = GooglePhotosPickedStore.findById(resolvePickedPath(), id);
        if (item == null) {
            throw new PhotoFrameException(PhotoErrorCode.NO_IMAGES, "Photo not found in selection.");
        }
        String label = item.filename != null && !item.filename.isEmpty() ? item.filename : id;
        try {
            boolean newlyCached = imageCacheService.cacheItem(item);
            Map<String, Object> body = new HashMap<>();
            body.put("success", true);
            body.put("id", id);
            body.put("filename", label);
            body.put("newlyCached", newlyCached);
            return body;
        } catch (Exception ex) {
            throw new PhotoFrameException(
                    PhotoErrorCode.GOOGLE_API_ERROR,
                    "Could not download \"" + label + "\": " + ex.getMessage(),
                    ex);
        }
    }

    private List<Map<String, Object>> buildToCacheList(List<GooglePhotosPickedStore.StoredPickedItem> incoming)
            throws Exception {
        Path pickedPath = resolvePickedPath();
        List<Map<String, Object>> toCache = new ArrayList<>();
        for (GooglePhotosPickedStore.StoredPickedItem item : GooglePhotosPickedStore.load(pickedPath)) {
            if (item.id == null || item.id.isEmpty()) {
                continue;
            }
            if (imageCacheService.isCached(item.id)) {
                continue;
            }
            Map<String, Object> row = new HashMap<>();
            row.put("id", item.id);
            row.put("filename", item.filename != null && !item.filename.isEmpty() ? item.filename : item.id);
            toCache.add(row);
        }
        return toCache;
    }

    public Map<String, Object> listPicked() throws Exception {
        Path pickedPath = resolvePickedPath();
        List<Map<String, Object>> items = new ArrayList<>();
        int cachedCount = 0;
        for (GooglePhotosPickedStore.StoredPickedItem item : GooglePhotosPickedStore.load(pickedPath)) {
            boolean cached = imageCacheService.isCached(item.id);
            if (cached) {
                cachedCount++;
            }
            Map<String, Object> row = new HashMap<>();
            row.put("id", item.id);
            row.put("filename", item.filename != null ? item.filename : "");
            row.put("mimeType", item.mimeType != null ? item.mimeType : "image/jpeg");
            row.put("cached", cached);
            row.put("thumbnailUrl", "/api/photos/serve/" + item.id + "?_=" + System.currentTimeMillis());
            items.add(row);
        }
        Map<String, Object> body = new HashMap<>();
        body.put("success", true);
        body.put("photoCount", items.size());
        body.put("cachedCount", cachedCount);
        body.put("items", items);
        body.put("slideshowUrl", "/");
        return body;
    }

    public Map<String, Object> pickedStatus() throws Exception {
        Map<String, Object> body = listPicked();
        body.put("pickUrl", PhotoApiResponse.PICK_PAGE_PATH);
        return body;
    }

    public Map<String, Object> removePicked(String id) throws Exception {
        Path pickedPath = resolvePickedPath();
        if (!GooglePhotosPickedStore.removeById(pickedPath, id)) {
            throw new PhotoFrameException(PhotoErrorCode.NO_IMAGES, "Photo not found in selection.");
        }
        imageCacheService.deleteCached(id);
        Map<String, Object> body = new HashMap<>();
        body.put("success", true);
        body.put("photoCount", GooglePhotosPickedStore.count(pickedPath));
        body.put("message", "Photo removed.");
        return body;
    }

    public Map<String, Object> clearPicked() throws Exception {
        Path pickedPath = resolvePickedPath();
        GooglePhotosPickedStore.clear(pickedPath);
        imageCacheService.clearAll();
        Map<String, Object> body = new HashMap<>();
        body.put("success", true);
        body.put("photoCount", 0);
        body.put("message", "All photos removed from selection.");
        return body;
    }

    private PickedMediaBatch listAllPickedMedia(String sessionId) throws Exception {
        GoogleCredential credential = credential();
        NetHttpTransport transport = GoogleNetHttpTransport.newTrustedTransport();
        List<GooglePhotosPickedStore.StoredPickedItem> photos = new ArrayList<>();
        int skippedVideos = 0;
        String pageToken = null;
        do {
            GenericUrl url = new GenericUrl(PICKER_BASE + "mediaItems");
            url.put("sessionId", sessionId);
            url.put("pageSize", 100);
            if (pageToken != null) {
                url.put("pageToken", pageToken);
            }
            HttpResponse response;
            try {
                response = transport.createRequestFactory(credential)
                        .buildGetRequest(url)
                        .execute();
            } catch (HttpResponseException ex) {
                throw GooglePickerApiErrors.toPhotoFrameException(ex);
            }
            JsonNode root = parseJson(response);
            JsonNode mediaItems = root.get("mediaItems");
            if (mediaItems != null && mediaItems.isArray()) {
                for (JsonNode item : mediaItems) {
                    String type = text(item, "type");
                    if ("VIDEO".equals(type)) {
                        skippedVideos++;
                        continue;
                    }
                    if (!"PHOTO".equals(type)) {
                        continue;
                    }
                    JsonNode mediaFile = item.get("mediaFile");
                    if (mediaFile == null) {
                        continue;
                    }
                    String baseUrl = text(mediaFile, "baseUrl");
                    String id = text(item, "id");
                    if (id.isEmpty() || baseUrl.isEmpty()) {
                        continue;
                    }
                    GooglePhotosPickedStore.StoredPickedItem stored = new GooglePhotosPickedStore.StoredPickedItem();
                    stored.id = id;
                    stored.baseUrl = baseUrl;
                    stored.mimeType = text(mediaFile, "mimeType");
                    if (stored.mimeType.isEmpty()) {
                        stored.mimeType = "image/jpeg";
                    }
                    stored.filename = text(mediaFile, "filename");
                    photos.add(stored);
                }
            }
            pageToken = text(root, "nextPageToken");
            if (pageToken.isEmpty()) {
                pageToken = null;
            }
        } while (pageToken != null);
        return new PickedMediaBatch(photos, skippedVideos);
    }

    private static final class PickedMediaBatch {
        private final List<GooglePhotosPickedStore.StoredPickedItem> photos;
        private final int skippedVideos;

        private PickedMediaBatch(List<GooglePhotosPickedStore.StoredPickedItem> photos, int skippedVideos) {
            this.photos = photos;
            this.skippedVideos = skippedVideos;
        }
    }

    private void deleteSession(String sessionId) {
        try {
            GoogleCredential credential = credential();
            NetHttpTransport transport = GoogleNetHttpTransport.newTrustedTransport();
            transport.createRequestFactory(credential)
                    .buildDeleteRequest(new GenericUrl(PICKER_BASE + "sessions/" + sessionId))
                    .execute();
        } catch (Exception ex) {
            log.debug("Picker session delete ignored: {}", ex.getMessage());
        }
    }

    private GoogleCredential credential() throws Exception {
        try {
            return GooglePhotosClientFactory.buildCredential(googlePhotosService.loadCredentials());
        } catch (GoogleJsonResponseException ex) {
            throw GooglePhotosApiErrors.toPhotoFrameException(ex);
        }
    }

    private Path resolvePickedPath() {
        Path path = Paths.get(config.getGooglePickedFile());
        if (!path.isAbsolute()) {
            Path projectRoot = Paths.get("").toAbsolutePath().getParent();
            if (projectRoot != null) {
                path = projectRoot.resolve(path).normalize();
            }
        }
        return path;
    }

    private static JsonNode parseJson(HttpResponse response) throws Exception {
        String body = response.parseAsString();
        if (body == null || body.isBlank()) {
            throw new PhotoFrameException(PhotoErrorCode.GOOGLE_API_ERROR, "Empty response from Google Photos Picker API.");
        }
        return MAPPER.readTree(body);
    }

    private static String text(JsonNode node, String field) {
        if (node == null || !node.has(field) || node.get(field).isNull()) {
            return "";
        }
        return node.get(field).asText("");
    }

    static long parseDurationMs(String duration, long defaultMs) {
        if (duration == null || duration.isBlank()) {
            return defaultMs;
        }
        String s = duration.trim();
        if (s.endsWith("s")) {
            s = s.substring(0, s.length() - 1).trim();
        }
        try {
            double seconds = Double.parseDouble(s);
            return Math.max(500, (long) (seconds * 1000));
        } catch (NumberFormatException ex) {
            return defaultMs;
        }
    }

    static String appendAutoclose(String pickerUri) {
        if (pickerUri == null || pickerUri.isEmpty()) {
            return pickerUri;
        }
        if (pickerUri.endsWith("/autoclose")) {
            return pickerUri;
        }
        return pickerUri.endsWith("/") ? pickerUri + "autoclose" : pickerUri + "/autoclose";
    }
}
