// Generated by Auto (Composer) - 2026-05-25
// Model: Composer
package com.mwa.photoframe.service;

import com.mwa.photoframe.config.PhotoFrameConfig;
import com.mwa.photoframe.source.GooglePhotosCredentials;
import com.mwa.photoframe.util.PhotoFramePaths;
import com.mwa.photoframe.util.PhotoFrameTraceLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Path;

@Service
public class GooglePhotosService {

    private static final Logger log = LoggerFactory.getLogger(GooglePhotosService.class);

    private final PhotoFrameConfig config;

    public GooglePhotosService(PhotoFrameConfig config) {
        this.config = config;
    }

    public GooglePhotosCredentials loadCredentials() throws IOException {
        Path credPath = resolveProjectRelativePath(config.getGoogleCredentialsPath());
        log.debug("Loading Google credentials from {}", credPath.toAbsolutePath());
        return GooglePhotosCredentials.load(credPath);
    }

    private Path resolveProjectRelativePath(String pathStr) {
        Path path = PhotoFramePaths.resolve(pathStr);
        PhotoFrameTraceLog.tracePath(log, "resolve-path", path);
        return path;
    }
}
