// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.service;

import com.mwa.photoframe.config.PhotoFrameConfig;
import com.mwa.photoframe.source.GooglePhotosCredentials;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

@Service
public class GooglePhotosService {

    private final PhotoFrameConfig config;

    public GooglePhotosService(PhotoFrameConfig config) {
        this.config = config;
    }

    public GooglePhotosCredentials loadCredentials() throws IOException {
        Path credPath = resolveProjectRelativePath(config.getGoogleCredentialsPath());
        return GooglePhotosCredentials.load(credPath);
    }

    private Path resolveProjectRelativePath(String pathStr) {
        Path path = Paths.get(pathStr);
        if (!path.isAbsolute()) {
            Path projectRoot = Paths.get("").toAbsolutePath().getParent();
            if (projectRoot != null) {
                path = projectRoot.resolve(path).normalize();
            }
        }
        return path;
    }
}
