// Generated by Auto (Composer) - 2026-05-30
// Model: Composer
package com.mwa.photoframe.service;

import com.mwa.photoframe.config.PhotoFrameConfig;
import com.mwa.photoframe.config.PhotoFrameStorageConfiguration;
import com.mwa.photoframe.source.GooglePhotosCredentialProvider;
import com.mwa.photoframe.source.GooglePhotosCredentials;
import com.mwa.photoframe.source.GooglePhotosPickedPhotoSource;
import com.mwa.photoframe.source.GooglePhotosPickedStore;
import com.mwa.photoframe.source.HeicImageConverter;
import com.mwa.photoframe.source.PhotoEntry;
import com.mwa.photoframe.storage.PhotoFrameStorageKeys;
import com.mwa.photoframe.util.PhotoFramePaths;
import com.mwa.photoframe.util.PhotoFrameTraceLog;
import com.photoframe.storage.PutOptions;
import com.photoframe.storage.StorageException;
import com.photoframe.storage.StorageObjectNotFoundException;
import com.photoframe.storage.StorageService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

@Service
public class GooglePhotosImageCacheService {

    private static final Logger log = LoggerFactory.getLogger(GooglePhotosImageCacheService.class);

    private final PhotoFrameConfig config;
    private final GooglePhotosService googlePhotosService;
    private final StorageService storage;
    private final String googleKeyPrefix;

    public GooglePhotosImageCacheService(
            PhotoFrameConfig config,
            GooglePhotosService googlePhotosService,
            StorageService storage) {
        this.config = config;
        this.googlePhotosService = googlePhotosService;
        this.storage = storage;
        this.googleKeyPrefix = config.getStorageGoogleKeyPrefix();
        log.debug("Google photo cache key prefix={}", googleKeyPrefix);
    }

    public String storageKey(String mediaId) {
        return PhotoFrameStorageKeys.googlePhotoJpeg(googleKeyPrefix, mediaId);
    }

    public boolean isCached(String mediaId) throws Exception {
        String key = storageKey(mediaId);
        if (storage.exists(key)) {
            return true;
        }
        return Files.isRegularFile(legacyCacheFile(mediaId));
    }

    public InputStream openCached(String mediaId) throws Exception {
        String key = storageKey(mediaId);
        try {
            return storage.get(key);
        } catch (StorageObjectNotFoundException ex) {
            Path legacy = legacyCacheFile(mediaId);
            if (Files.isRegularFile(legacy)) {
                log.debug("Serving legacy cache file for id={} path={}", mediaId, legacy);
                return Files.newInputStream(legacy);
            }
            throw ex;
        }
    }

    public void saveJpeg(String mediaId, byte[] jpegBytes) throws Exception {
        String key = storageKey(mediaId);
        log.debug("Storage put id={} key={} bytes={}", mediaId, key, jpegBytes.length);
        storage.put(
                key,
                new ByteArrayInputStream(jpegBytes),
                PutOptions.builder()
                        .contentType("image/jpeg")
                        .metadata(Map.of("photoframe.mediaId", mediaId))
                        .overwrite(true)
                        .build());
    }

    public void saveFromGoogle(
            GooglePhotosPickedStore.StoredPickedItem item,
            GooglePhotosCredentialProvider credentialProvider) throws Exception {
        if (item == null || item.id == null || item.id.isEmpty() || item.baseUrl == null) {
            throw new IllegalArgumentException("Photo metadata is incomplete.");
        }
        log.debug("Cache download start id={}", item.id);
        String mime = item.mimeType != null ? item.mimeType : "image/jpeg";
        PhotoEntry entry = PhotoEntry.google(item.id, item.baseUrl, mime);
        byte[] bytes = PhotoCatalogService.fetchGooglePhotoBytes(entry, credentialProvider);
        String label = item.filename != null ? item.filename : item.id;
        bytes = HeicImageConverter.toCacheJpeg(bytes, mime, label);
        saveJpeg(item.id, bytes);
        log.debug("Cache download OK id={} bytes={}", item.id, bytes.length);
    }

    /** Download one picked item to storage. Returns false if already cached. */
    public boolean cacheItem(GooglePhotosPickedStore.StoredPickedItem item) throws Exception {
        if (item == null || item.id == null || item.id.isEmpty()) {
            throw new IllegalArgumentException("Missing photo id.");
        }
        if (isCached(item.id)) {
            log.debug("Cache skip (already cached) id={}", item.id);
            return false;
        }
        GooglePhotosCredentials creds = googlePhotosService.loadCredentials();
        Path pickedPath = resolvePickedPath();
        GooglePhotosPickedPhotoSource provider = new GooglePhotosPickedPhotoSource(creds, pickedPath);
        saveFromGoogle(item, provider);
        return true;
    }

    public int warmItems(List<GooglePhotosPickedStore.StoredPickedItem> items) {
        if (items == null || items.isEmpty()) {
            return 0;
        }
        int cached = 0;
        try {
            GooglePhotosCredentials creds = googlePhotosService.loadCredentials();
            Path pickedPath = resolvePickedPath();
            GooglePhotosPickedPhotoSource provider = new GooglePhotosPickedPhotoSource(creds, pickedPath);
            for (GooglePhotosPickedStore.StoredPickedItem item : items) {
                try {
                    if (isCached(item.id)) {
                        continue;
                    }
                    saveFromGoogle(item, provider);
                    cached++;
                } catch (Exception ex) {
                    log.warn("Could not cache photo {}: {}", item.id, ex.getMessage(), ex);
                }
            }
        } catch (Exception ex) {
            log.warn("Photo cache warm-up failed: {}", ex.getMessage(), ex);
        }
        return cached;
    }

    public int warmAllPicked() throws Exception {
        Path pickedPath = resolvePickedPath();
        return warmItems(GooglePhotosPickedStore.load(pickedPath));
    }

    public void deleteCached(String mediaId) {
        try {
            storage.delete(storageKey(mediaId));
        } catch (StorageException ex) {
            log.debug("Storage delete id={}: {}", mediaId, ex.getMessage());
        }
        try {
            Path legacy = legacyCacheFile(mediaId);
            Files.deleteIfExists(legacy);
            Files.deleteIfExists(legacy.resolveSibling(legacy.getFileName().toString() + ".metadata.json"));
        } catch (Exception ex) {
            log.debug("Legacy cache delete id={}: {}", mediaId, ex.getMessage());
        }
    }

    public void clearAll() throws Exception {
        Path pickedPath = resolvePickedPath();
        for (GooglePhotosPickedStore.StoredPickedItem item : GooglePhotosPickedStore.load(pickedPath)) {
            if (item.id != null && !item.id.isEmpty()) {
                deleteCached(item.id);
            }
        }
        clearLegacyFlatCache();
    }

    /** Pre-storage-lib layout: flat {@code {id}.jpg} in {@code photoframe.google.cache.dir}. */
    private Path legacyCacheFile(String mediaId) {
        String safe = mediaId.replaceAll("[^a-zA-Z0-9._-]", "_");
        return resolveLegacyCacheDir().resolve(safe + ".jpg");
    }

    private Path resolveLegacyCacheDir() {
        return PhotoFrameStorageConfiguration.resolveRootPath(config.getGoogleCacheDir());
    }

    private void clearLegacyFlatCache() {
        Path dir = resolveLegacyCacheDir();
        PhotoFrameTraceLog.tracePath(log, "cache-clear-legacy", dir);
        if (!Files.isDirectory(dir)) {
            return;
        }
        try (var stream = Files.list(dir)) {
            for (Path p : stream.toList()) {
                String name = p.getFileName().toString();
                if (Files.isRegularFile(p) && !name.contains("/")) {
                    Files.deleteIfExists(p);
                }
            }
        } catch (Exception ex) {
            log.warn("Legacy cache clear failed: {}", ex.getMessage());
        }
    }

    private Path resolvePickedPath() {
        return PhotoFramePaths.resolve(config.getGooglePickedFile());
    }
}
