// Generated by Auto (Composer) - 2026-05-22
// Model: Composer
package com.mwa.photoframe.service;

import com.mwa.photoframe.config.PhotoFrameConfig;
import com.mwa.photoframe.source.GooglePhotosCredentialProvider;
import com.mwa.photoframe.source.GooglePhotosCredentials;
import com.mwa.photoframe.source.GooglePhotosImageCache;
import com.mwa.photoframe.source.GooglePhotosPickedPhotoSource;
import com.mwa.photoframe.source.GooglePhotosPickedStore;
import com.mwa.photoframe.source.HeicImageConverter;
import com.mwa.photoframe.source.PhotoEntry;
import com.mwa.photoframe.util.PhotoFrameTraceLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

@Service
public class GooglePhotosImageCacheService {

    private static final Logger log = LoggerFactory.getLogger(GooglePhotosImageCacheService.class);

    private final PhotoFrameConfig config;
    private final GooglePhotosService googlePhotosService;

    public GooglePhotosImageCacheService(PhotoFrameConfig config, GooglePhotosService googlePhotosService) {
        this.config = config;
        this.googlePhotosService = googlePhotosService;
    }

    public Path cacheDir() throws Exception {
        return GooglePhotosImageCache.resolveCacheDir(resolveCachePath());
    }

    public Path cachedFile(String mediaId) throws Exception {
        return GooglePhotosImageCache.cacheFile(cacheDir(), mediaId);
    }

    public boolean isCached(String mediaId) throws Exception {
        return GooglePhotosImageCache.isCached(cacheDir(), mediaId);
    }

    public void saveFromGoogle(
            GooglePhotosPickedStore.StoredPickedItem item,
            GooglePhotosCredentialProvider credentialProvider) throws Exception {
        if (item == null || item.id == null || item.id.isEmpty() || item.baseUrl == null) {
            throw new IllegalArgumentException("Photo metadata is incomplete.");
        }
        log.debug("Cache download start id={}", item.id);
        String mime = item.mimeType != null ? item.mimeType : "image/jpeg";
        PhotoEntry entry = PhotoEntry.google(item.id, item.baseUrl, mime);
        byte[] bytes = PhotoCatalogService.fetchGooglePhotoBytes(entry, credentialProvider);
        String label = item.filename != null ? item.filename : item.id;
        bytes = HeicImageConverter.toCacheJpeg(bytes, mime, label);
        GooglePhotosImageCache.saveJpeg(cacheDir(), item.id, bytes);
        log.debug("Cache download OK id={} bytes={}", item.id, bytes.length);
    }

    /** Download one picked item to local cache. Returns false if already cached. */
    public boolean cacheItem(GooglePhotosPickedStore.StoredPickedItem item) throws Exception {
        if (item == null || item.id == null || item.id.isEmpty()) {
            throw new IllegalArgumentException("Missing photo id.");
        }
        if (isCached(item.id)) {
            log.debug("Cache skip (already cached) id={}", item.id);
            return false;
        }
        GooglePhotosCredentials creds = googlePhotosService.loadCredentials();
        Path pickedPath = resolvePickedPath();
        GooglePhotosPickedPhotoSource provider = new GooglePhotosPickedPhotoSource(creds, pickedPath);
        saveFromGoogle(item, provider);
        return true;
    }

    public int warmItems(List<GooglePhotosPickedStore.StoredPickedItem> items) {
        if (items == null || items.isEmpty()) {
            return 0;
        }
        int cached = 0;
        try {
            GooglePhotosCredentials creds = googlePhotosService.loadCredentials();
            Path pickedPath = resolvePickedPath();
            GooglePhotosPickedPhotoSource provider = new GooglePhotosPickedPhotoSource(creds, pickedPath);
            for (GooglePhotosPickedStore.StoredPickedItem item : items) {
                try {
                    if (isCached(item.id)) {
                        continue;
                    }
                    saveFromGoogle(item, provider);
                    cached++;
                } catch (Exception ex) {
                    log.warn("Could not cache photo {}: {}", item.id, ex.getMessage(), ex);
                }
            }
        } catch (Exception ex) {
            log.warn("Photo cache warm-up failed: {}", ex.getMessage(), ex);
        }
        return cached;
    }

    public int warmAllPicked() throws Exception {
        Path pickedPath = resolvePickedPath();
        return warmItems(GooglePhotosPickedStore.load(pickedPath));
    }

    public void deleteCached(String mediaId) {
        try {
            Path dir = cacheDir();
            GooglePhotosImageCache.delete(dir, mediaId);
        } catch (Exception ex) {
            log.warn("Cache delete failed id={}: {}", mediaId, ex.getMessage(), ex);
        }
    }

    public void clearAll() throws Exception {
        GooglePhotosImageCache.clearAll(cacheDir());
    }

    private Path resolvePickedPath() {
        Path path = Paths.get(config.getGooglePickedFile());
        if (!path.isAbsolute()) {
            Path projectRoot = Paths.get("").toAbsolutePath().getParent();
            if (projectRoot != null) {
                path = projectRoot.resolve(path).normalize();
            }
        }
        return path;
    }

    private Path resolveCachePath() {
        Path path = Paths.get(config.getGoogleCacheDir());
        if (!path.isAbsolute()) {
            Path projectRoot = Paths.get("").toAbsolutePath().getParent();
            if (projectRoot != null) {
                path = projectRoot.resolve(path).normalize();
            }
        }
        return path;
    }
}
