// Generated by Auto (Composer) - 2026-05-21
package com.mwa.photoframe.service;

import com.google.api.client.googleapis.auth.oauth2.GoogleCredential;
import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.HttpResponseException;
import com.google.api.client.http.HttpTransport;
import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.mwa.photoframe.api.PhotoApiResponse;
import com.mwa.photoframe.api.PhotoErrorCode;
import com.mwa.photoframe.api.PhotoFrameException;
import com.mwa.photoframe.config.PhotoFrameConfig;
import com.mwa.photoframe.source.GooglePhotosCredentialProvider;
import com.mwa.photoframe.source.GooglePhotosImageCache;
import com.mwa.photoframe.source.GooglePhotosCredentials;
import com.mwa.photoframe.source.GooglePhotosPickedPhotoSource;
import com.mwa.photoframe.source.GooglePhotosPickedStore;
import com.mwa.photoframe.source.HeicImageConverter;
import com.mwa.photoframe.source.LocalFolderPhotoSource;
import com.mwa.photoframe.source.PhotoEntry;
import com.mwa.photoframe.source.PhotoSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.atomic.AtomicInteger;

@Service
public class PhotoCatalogService {

    private static final Logger log = LoggerFactory.getLogger(PhotoCatalogService.class);

    private final PhotoFrameConfig config;
    private final GooglePhotosService googlePhotosService;
    private final GooglePhotosImageCacheService imageCacheService;
    private final AtomicInteger index = new AtomicInteger(0);
    private volatile List<PhotoEntry> catalog = Collections.emptyList();
    private volatile String loadedKey = "";
    private volatile LocalFolderPhotoSource localSource;
    private volatile GooglePhotosCredentialProvider googleCredentialProvider;

    public PhotoCatalogService(
            PhotoFrameConfig config,
            GooglePhotosService googlePhotosService,
            GooglePhotosImageCacheService imageCacheService) {
        this.config = config;
        this.googlePhotosService = googlePhotosService;
        this.imageCacheService = imageCacheService;
    }

    public void invalidateCatalog() {
        loadedKey = "";
        catalog = Collections.emptyList();
        index.set(0);
    }

    public synchronized void ensureCatalog(String folderParam) throws Exception {
        String source = configuredSource();
        String key = source + "|picked|"
                + (folderParam != null ? folderParam : config.getLocalFolder());
        if (key.equals(loadedKey) && !catalog.isEmpty()) {
            return;
        }
        PhotoSource photoSource = buildSource(source, folderParam);
        List<PhotoEntry> loaded = photoSource.loadCatalog();
        if (loaded.isEmpty()) {
            if ("google".equals(source)) {
                throw new PhotoFrameException(
                        PhotoErrorCode.NO_IMAGES,
                        "0 images available. Choose photos from your Google Photos library at "
                                + PhotoApiResponse.PICK_PAGE_PATH
                                + ".");
            }
            throw new PhotoFrameException(
                    PhotoErrorCode.NO_IMAGES,
                    "0 images available in local folder.");
        }
        catalog = loaded;
        index.set(0);
        loadedKey = key;
        log.info("Catalog ready: {} photos, source={}", catalog.size(), source);
    }

    public PhotoEntry nextPhoto(String folderParam) throws Exception {
        ensureCatalog(folderParam);
        int i = index.getAndIncrement();
        if (i >= catalog.size()) {
            index.set(0);
            i = 0;
        }
        return catalog.get(i);
    }

    public PhotoEntry findById(String id) throws Exception {
        for (PhotoEntry entry : catalog) {
            if (entry.getId().equals(id)) {
                return entry;
            }
        }
        return null;
    }

    public Resource loadImageResource(PhotoEntry entry) throws Exception {
        if (entry.isLocal()) {
            if (localSource == null) {
                throw new IllegalStateException("Local source not initialized");
            }
            Path file = localSource.resolveFile(entry);
            if (!Files.isRegularFile(file)) {
                throw new IllegalStateException("File not found: " + file);
            }
            if (HeicImageConverter.isHeicPath(file)) {
                byte[] jpeg = HeicImageConverter.toJpeg(file);
                return new ByteArrayResource(jpeg);
            }
            return new FileSystemResource(file);
        }
        if (entry.isGoogle()) {
            Path cached = imageCacheService.cachedFile(entry.getId());
            if (Files.isRegularFile(cached)) {
                return new FileSystemResource(cached);
            }
            if (googleCredentialProvider == null) {
                throw new IllegalStateException("Google source not initialized");
            }
            byte[] imageBytes = fetchGooglePhotoBytes(entry, googleCredentialProvider);
            if (HeicImageConverter.isHeicMime(entry.getMimeType())) {
                imageBytes = HeicImageConverter.toJpeg(imageBytes);
            }
            try {
                GooglePhotosImageCache.saveJpeg(imageCacheService.cacheDir(), entry.getId(), imageBytes);
            } catch (IOException saveEx) {
                log.warn("Could not write image cache for {}: {}", entry.getId(), saveEx.getMessage());
            }
            return new ByteArrayResource(imageBytes);
        }
        throw new IllegalStateException("Unknown source type: " + entry.getSourceType());
    }

    static byte[] fetchGooglePhotoBytes(PhotoEntry entry, GooglePhotosCredentialProvider credentialProvider)
            throws Exception {
        String baseUrl = entry.getGoogleBaseUrl();
        HttpResponseException lastError = null;
        for (String url : googleFetchUrlCandidates(baseUrl)) {
            try {
                return executeGooglePhotoFetch(credentialProvider, url);
            } catch (HttpResponseException ex) {
                lastError = ex;
                if (ex.getStatusCode() != 403 && ex.getStatusCode() != 404) {
                    throw mapGooglePhotoFetchError(ex);
                }
            }
        }
        if (lastError != null) {
            throw mapGooglePhotoFetchError(lastError);
        }
        throw new PhotoFrameException(PhotoErrorCode.GOOGLE_API_ERROR, "Missing Google Photos image URL.");
    }

    private static byte[] executeGooglePhotoFetch(
            GooglePhotosCredentialProvider credentialProvider, String url) throws Exception {
        GoogleCredential credential = credentialProvider.getCredential();
        HttpTransport transport = GoogleNetHttpTransport.newTrustedTransport();
        HttpResponse response = transport.createRequestFactory(credential)
                .buildGetRequest(new GenericUrl(url))
                .execute();
        try (InputStream in = response.getContent()) {
            return in.readAllBytes();
        }
    }

    static String[] googleFetchUrlCandidates(String baseUrl) {
        if (baseUrl == null || baseUrl.isEmpty()) {
            return new String[0];
        }
        if (baseUrl.indexOf('=') >= 0) {
            return new String[] { baseUrl };
        }
        return new String[] {
                baseUrl + "=w2048-h1536",
                baseUrl + "=d"
        };
    }

    static String googleDisplayUrl(String baseUrl) {
        if (baseUrl == null || baseUrl.isEmpty()) {
            return baseUrl;
        }
        if (baseUrl.indexOf('=') >= 0) {
            return baseUrl;
        }
        return baseUrl + "=w2048-h1536";
    }

    private static PhotoFrameException mapGooglePhotoFetchError(HttpResponseException ex) {
        int status = ex.getStatusCode();
        if (status == 403 || status == 404) {
            return new PhotoFrameException(
                    PhotoErrorCode.GOOGLE_API_ERROR,
                    "This photo is not on the Mac yet. Open " + PhotoApiResponse.PICK_PAGE_PATH
                            + ", use “Add photos from Google Photos”, and select your photos again "
                            + "(PhotoFrame will download and cache them).",
                    ex);
        }
        if (status == 401) {
            return new PhotoFrameException(
                    PhotoErrorCode.AUTH_FAILED,
                    PhotoErrorCode.AUTH_FAILED.getDefaultMessage(),
                    ex);
        }
        return new PhotoFrameException(
                PhotoErrorCode.GOOGLE_API_ERROR,
                PhotoErrorCode.GOOGLE_API_ERROR.getDefaultMessage() + " (HTTP " + status + ")",
                ex);
    }

    public int getDefaultTimerSeconds() {
        return config.getDefaultTimerSeconds();
    }

    public String getDefaultSource() {
        return config.getDefaultSource();
    }

    private PhotoSource buildSource(String source, String folderParam) throws Exception {
        if ("google".equals(source)) {
            try {
                return buildGoogleSource();
            } catch (PhotoFrameException ex) {
                throw ex;
            } catch (java.io.IOException ex) {
                throw new PhotoFrameException(
                        PhotoErrorCode.AUTH_CONFIG,
                        PhotoErrorCode.AUTH_CONFIG.getDefaultMessage() + " " + ex.getMessage(),
                        ex);
            }
        }
        Path folder = resolveLocalFolder(folderParam);
        localSource = new LocalFolderPhotoSource(folder);
        googleCredentialProvider = null;
        return localSource;
    }

    private PhotoSource buildGoogleSource() throws Exception {
        GooglePhotosCredentials creds = googlePhotosService.loadCredentials();
        Path pickedPath = resolveProjectRelativePath(config.getGooglePickedFile());
        GooglePhotosPickedPhotoSource picked = new GooglePhotosPickedPhotoSource(creds, pickedPath);
        googleCredentialProvider = picked;
        localSource = null;
        return picked;
    }

    private Path resolveProjectRelativePath(String pathStr) {
        Path path = Paths.get(pathStr);
        if (!path.isAbsolute()) {
            Path projectRoot = Paths.get("").toAbsolutePath().getParent();
            if (projectRoot != null) {
                path = projectRoot.resolve(path).normalize();
            }
        }
        return path;
    }

    private Path resolveLocalFolder(String folderParam) {
        String pathStr = folderParam != null && !folderParam.trim().isEmpty()
                ? folderParam.trim()
                : config.getLocalFolder();
        Path folder = Paths.get(pathStr);
        if (!folder.isAbsolute()) {
            Path projectRoot = Paths.get("").toAbsolutePath().getParent();
            if (projectRoot != null) {
                folder = projectRoot.resolve(folder).normalize();
            }
        }
        return folder;
    }

    private String configuredSource() {
        return normalizeSource(config.getDefaultSource());
    }

    private static String normalizeSource(String source) {
        String s = source.trim().toLowerCase(Locale.ROOT);
        if ("google".equals(s) || "googlephotos".equals(s) || "google_photos".equals(s)) {
            return "google";
        }
        return "local";
    }

}
