// Generated by Auto (Composer) - 2026-05-21
package com.mwa.photoframe.service;

import com.google.api.client.googleapis.auth.oauth2.GoogleCredential;
import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.HttpResponseException;
import com.google.api.client.http.HttpTransport;
import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.mwa.photoframe.api.PhotoApiResponse;
import com.mwa.photoframe.api.PhotoErrorCode;
import com.mwa.photoframe.api.PhotoFrameException;
import com.mwa.photoframe.config.PhotoFrameConfig;
import com.mwa.photoframe.source.GooglePhotosCredentialProvider;
import com.mwa.photoframe.source.GooglePhotosCredentials;
import com.mwa.photoframe.source.GooglePhotosPickedPhotoSource;
import com.mwa.photoframe.source.GooglePhotosPickedStore;
import com.mwa.photoframe.source.HeicImageConverter;
import com.mwa.photoframe.source.LocalFolderPhotoSource;
import com.mwa.photoframe.source.PhotoEntry;
import com.mwa.photoframe.source.PhotoSource;
import com.mwa.photoframe.util.GoogleHttpTrace;
import com.mwa.photoframe.util.PhotoFramePaths;
import com.mwa.photoframe.util.PhotoFrameTraceLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.InputStreamResource;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.atomic.AtomicInteger;

@Service
public class PhotoCatalogService {

    private static final Logger log = LoggerFactory.getLogger(PhotoCatalogService.class);

    private final PhotoFrameConfig config;
    private final GooglePhotosService googlePhotosService;
    private final GooglePhotosImageCacheService imageCacheService;
    private final AtomicInteger index = new AtomicInteger(0);
    private volatile List<PhotoEntry> catalog = Collections.emptyList();
    private volatile String loadedKey = "";
    private volatile LocalFolderPhotoSource localSource;
    private volatile GooglePhotosCredentialProvider googleCredentialProvider;

    public PhotoCatalogService(
            PhotoFrameConfig config,
            GooglePhotosService googlePhotosService,
            GooglePhotosImageCacheService imageCacheService) {
        this.config = config;
        this.googlePhotosService = googlePhotosService;
        this.imageCacheService = imageCacheService;
    }

    public void invalidateCatalog() {
        log.debug("Catalog invalidated (was {} photos)", catalog.size());
        loadedKey = "";
        catalog = Collections.emptyList();
        index.set(0);
    }

    public synchronized void ensureCatalog(String folderParam) throws Exception {
        String source = configuredSource();
        String key = source + "|picked|"
                + (folderParam != null ? folderParam : config.getLocalFolder());
        if (key.equals(loadedKey) && !catalog.isEmpty()) {
            log.trace("Catalog cache hit key={} size={}", key, catalog.size());
            return;
        }
        log.debug("Catalog load start source={} folderParam={}", source, folderParam);
        PhotoSource photoSource = buildSource(source, folderParam);
        List<PhotoEntry> loaded = photoSource.loadCatalog();
        if (loaded.isEmpty()) {
            if ("google".equals(source)) {
                throw new PhotoFrameException(
                        PhotoErrorCode.NO_IMAGES,
                        "0 images available. Choose photos from your Google Photos library at "
                                + PhotoApiResponse.PICK_PAGE_PATH
                                + ".");
            }
            throw new PhotoFrameException(
                    PhotoErrorCode.NO_IMAGES,
                    "0 images available in local folder.");
        }
        catalog = loaded;
        index.set(0);
        loadedKey = key;
        log.info("Catalog ready: {} photos, source={}", catalog.size(), source);
    }

    public PhotoEntry nextPhoto(String folderParam) throws Exception {
        ensureCatalog(folderParam);
        int i = index.getAndIncrement();
        log.trace("Catalog next index={}/{}", i, catalog.size());
        if (i >= catalog.size()) {
            index.set(0);
            i = 0;
        }
        return catalog.get(i);
    }

    public PhotoEntry findById(String id) throws Exception {
        for (PhotoEntry entry : catalog) {
            if (entry.getId().equals(id)) {
                return entry;
            }
        }
        return null;
    }

    public Resource loadImageResource(PhotoEntry entry) throws Exception {
        log.debug("Load image id={} source={}", entry.getId(), entry.getSourceType());
        if (entry.isLocal()) {
            if (localSource == null) {
                throw new IllegalStateException("Local source not initialized");
            }
            Path file = localSource.resolveFile(entry);
            PhotoFrameTraceLog.tracePath(log, "serve-local", file);
            if (!Files.isRegularFile(file)) {
                log.error("IO serve-local missing file path={}", file.toAbsolutePath());
                throw new IllegalStateException("File not found: " + file);
            }
            if (HeicImageConverter.isHeicPath(file)) {
                byte[] jpeg = HeicImageConverter.toJpeg(file);
                log.debug("IO serve-local HEIC→JPEG path={} bytes={}", file.toAbsolutePath(), jpeg.length);
                return new ByteArrayResource(jpeg);
            }
            PhotoFrameTraceLog.debugPath(log, "serve-local", file);
            return new FileSystemResource(file);
        }
        if (entry.isGoogle()) {
            if (imageCacheService.isCached(entry.getId())) {
                log.debug("Google serve storage hit id={} key={}", entry.getId(), imageCacheService.storageKey(entry.getId()));
                return new InputStreamResource(imageCacheService.openCached(entry.getId()));
            }
            log.debug("Google serve cache-miss id={} — fetching", entry.getId());
            if (googleCredentialProvider == null) {
                throw new IllegalStateException("Google source not initialized");
            }
            byte[] imageBytes = fetchGooglePhotoBytes(entry, googleCredentialProvider);
            String label = entry.getId();
            imageBytes = HeicImageConverter.toCacheJpeg(imageBytes, entry.getMimeType(), label);
            try {
                imageCacheService.saveJpeg(entry.getId(), imageBytes);
            } catch (Exception saveEx) {
                log.warn("Could not store image in storage for {}: {}", entry.getId(), saveEx.getMessage(), saveEx);
            }
            return new ByteArrayResource(imageBytes);
        }
        throw new IllegalStateException("Unknown source type: " + entry.getSourceType());
    }

    static byte[] fetchGooglePhotoBytes(PhotoEntry entry, GooglePhotosCredentialProvider credentialProvider)
            throws Exception {
        String baseUrl = entry.getGoogleBaseUrl();
        HttpResponseException lastError = null;
        for (String url : googleFetchUrlCandidates(baseUrl, entry.getMimeType())) {
            try {
                byte[] bytes = executeGooglePhotoFetch(credentialProvider, url);
                log.debug("Google photo fetch OK id={} bytes={}", entry.getId(), bytes.length);
                return bytes;
            } catch (HttpResponseException ex) {
                lastError = ex;
                log.debug("Google photo fetch attempt failed id={} status={}", entry.getId(), ex.getStatusCode());
                if (ex.getStatusCode() != 403 && ex.getStatusCode() != 404) {
                    throw mapGooglePhotoFetchError(ex);
                }
            }
        }
        if (lastError != null) {
            throw mapGooglePhotoFetchError(lastError);
        }
        throw new PhotoFrameException(PhotoErrorCode.GOOGLE_API_ERROR, "Missing Google Photos image URL.");
    }

    private static byte[] executeGooglePhotoFetch(
            GooglePhotosCredentialProvider credentialProvider, String url) throws Exception {
        GoogleCredential credential = credentialProvider.getCredential();
        HttpTransport transport = GoogleNetHttpTransport.newTrustedTransport();
        HttpResponse response = GoogleHttpTrace.executeGet(
                log, "google-photo-download", transport, credential, new GenericUrl(url));
        try (InputStream in = response.getContent()) {
            byte[] bytes = in.readAllBytes();
            log.debug("Google photo download body bytes={}", bytes.length);
            return bytes;
        }
    }

    static String[] googleFetchUrlCandidates(String baseUrl, String mimeType) {
        if (baseUrl == null || baseUrl.isEmpty()) {
            return new String[0];
        }
        if (baseUrl.indexOf('=') >= 0) {
            return new String[] { baseUrl };
        }
        if (HeicImageConverter.isHeicMime(mimeType)) {
            return new String[] {
                    baseUrl + "=d",
                    baseUrl + "=w2048-h1536",
                    baseUrl + "=w0"
            };
        }
        return new String[] {
                baseUrl + "=w2048-h1536",
                baseUrl + "=d"
        };
    }

    static String googleDisplayUrl(String baseUrl) {
        if (baseUrl == null || baseUrl.isEmpty()) {
            return baseUrl;
        }
        if (baseUrl.indexOf('=') >= 0) {
            return baseUrl;
        }
        return baseUrl + "=w2048-h1536";
    }

    private static PhotoFrameException mapGooglePhotoFetchError(HttpResponseException ex) {
        int status = ex.getStatusCode();
        if (status == 403 || status == 404) {
            return new PhotoFrameException(
                    PhotoErrorCode.GOOGLE_API_ERROR,
                    "This photo is not on the Mac yet. Open " + PhotoApiResponse.PICK_PAGE_PATH
                            + ", use “Add photos from Google Photos”, and select your photos again "
                            + "(PhotoFrame will download and cache them).",
                    ex);
        }
        if (status == 401) {
            return new PhotoFrameException(
                    PhotoErrorCode.AUTH_FAILED,
                    PhotoErrorCode.AUTH_FAILED.getDefaultMessage(),
                    ex);
        }
        return new PhotoFrameException(
                PhotoErrorCode.GOOGLE_API_ERROR,
                PhotoErrorCode.GOOGLE_API_ERROR.getDefaultMessage() + " (HTTP " + status + ")",
                ex);
    }

    public int getDefaultTimerSeconds() {
        return config.getDefaultTimerSeconds();
    }

    public String getDefaultSource() {
        return config.getDefaultSource();
    }

    private PhotoSource buildSource(String source, String folderParam) throws Exception {
        if ("google".equals(source)) {
            try {
                return buildGoogleSource();
            } catch (PhotoFrameException ex) {
                throw ex;
            } catch (java.io.IOException ex) {
                throw new PhotoFrameException(
                        PhotoErrorCode.AUTH_CONFIG,
                        PhotoErrorCode.AUTH_CONFIG.getDefaultMessage() + " " + ex.getMessage(),
                        ex);
            }
        }
        Path folder = resolveLocalFolder(folderParam);
        PhotoFrameTraceLog.tracePath(log, "catalog-local-folder", folder);
        localSource = new LocalFolderPhotoSource(folder);
        googleCredentialProvider = null;
        return localSource;
    }

    private PhotoSource buildGoogleSource() throws Exception {
        GooglePhotosCredentials creds = googlePhotosService.loadCredentials();
        Path pickedPath = resolveProjectRelativePath(config.getGooglePickedFile());
        PhotoFrameTraceLog.tracePath(log, "catalog-google-picked", pickedPath);
        GooglePhotosPickedPhotoSource picked = new GooglePhotosPickedPhotoSource(creds, pickedPath);
        googleCredentialProvider = picked;
        localSource = null;
        return picked;
    }

    private Path resolveProjectRelativePath(String pathStr) {
        return PhotoFramePaths.resolve(pathStr);
    }

    private Path resolveLocalFolder(String folderParam) {
        String pathStr = folderParam != null && !folderParam.trim().isEmpty()
                ? folderParam.trim()
                : config.getLocalFolder();
        return PhotoFramePaths.resolve(pathStr);
    }

    private String configuredSource() {
        return normalizeSource(config.getDefaultSource());
    }

    private static String normalizeSource(String source) {
        String s = source.trim().toLowerCase(Locale.ROOT);
        if ("google".equals(s) || "googlephotos".equals(s) || "google_photos".equals(s)) {
            return "google";
        }
        return "local";
    }

}
