// Generated by Auto (Composer) - 2026-05-22
// Model: Composer
package com.mwa.photoframe.service;

import com.mwa.photoframe.config.PhotoFrameConfig;
import com.mwa.photoframe.source.SlideshowDisplaySettings;
import com.mwa.photoframe.source.SlideshowDisplaySettingsStore;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

@Service
public class SlideshowDisplaySettingsService {

    private final PhotoFrameConfig config;

    public SlideshowDisplaySettingsService(PhotoFrameConfig config) {
        this.config = config;
    }

    public SlideshowDisplaySettings get() throws IOException {
        return SlideshowDisplaySettingsStore.load(resolvePath(), config.getDefaultTimerSeconds());
    }

    public SlideshowDisplaySettings save(SlideshowDisplaySettings settings) throws IOException {
        return SlideshowDisplaySettingsStore.save(resolvePath(), settings);
    }

    private Path resolvePath() {
        return Paths.get(config.getDisplaySettingsFile()).toAbsolutePath().normalize();
    }
}
