// Generated by Auto (Composer) - 2026-05-22
// Model: Composer
package com.mwa.photoframe.service;

import com.mwa.photoframe.config.PhotoFrameConfig;
import com.mwa.photoframe.source.SlideshowDisplaySettings;
import com.mwa.photoframe.source.SlideshowDisplaySettingsStore;
import com.mwa.photoframe.util.PhotoFramePaths;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Path;

@Service
public class SlideshowDisplaySettingsService {

    private static final Logger log = LoggerFactory.getLogger(SlideshowDisplaySettingsService.class);

    private final PhotoFrameConfig config;

    public SlideshowDisplaySettingsService(PhotoFrameConfig config) {
        this.config = config;
    }

    public SlideshowDisplaySettings get() throws IOException {
        log.debug("Display settings load");
        return SlideshowDisplaySettingsStore.load(resolvePath(), config.getDefaultTimerSeconds());
    }

    public SlideshowDisplaySettings save(SlideshowDisplaySettings settings) throws IOException {
        log.debug("Display settings save");
        return SlideshowDisplaySettingsStore.save(resolvePath(), settings);
    }

    private Path resolvePath() {
        return PhotoFramePaths.resolve(config.getDisplaySettingsFile());
    }
}
