// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.api;

import com.google.api.client.googleapis.json.GoogleJsonResponseException;

public final class GooglePhotosApiErrors {

    private GooglePhotosApiErrors() {
    }

    public static PhotoFrameException toPhotoFrameException(GoogleJsonResponseException ex) {
        int status = ex.getStatusCode();
        String detail = ex.getDetails() != null ? ex.getDetails().getMessage() : ex.getMessage();
        if (detail == null || detail.isEmpty()) {
            detail = "HTTP " + status;
        }
        if (status == 401) {
            return new PhotoFrameException(
                    PhotoErrorCode.AUTH_FAILED,
                    PhotoErrorCode.AUTH_FAILED.getDefaultMessage() + " (" + detail + ")",
                    ex);
        }
        if (status == 403) {
            if (detail.toLowerCase().contains("insufficient")
                    || detail.toLowerCase().contains("scope")) {
                return new PhotoFrameException(
                        PhotoErrorCode.AUTH_FAILED,
                        "Google Photos scope error: re-authorize with appendonly and readonly.appcreateddata. "
                                + detail,
                        ex);
            }
            return new PhotoFrameException(PhotoErrorCode.AUTH_FAILED, detail, ex);
        }
        if (status == 404) {
            return new PhotoFrameException(
                    PhotoErrorCode.GOOGLE_API_ERROR,
                    "Google Photos resource not found. " + detail,
                    ex);
        }
        return new PhotoFrameException(
                PhotoErrorCode.GOOGLE_API_ERROR,
                PhotoErrorCode.GOOGLE_API_ERROR.getDefaultMessage() + " " + detail,
                ex);
    }

    public static RuntimeException wrap(Exception ex) {
        if (ex instanceof PhotoFrameException) {
            return (PhotoFrameException) ex;
        }
        if (ex instanceof GoogleJsonResponseException) {
            return toPhotoFrameException((GoogleJsonResponseException) ex);
        }
        Throwable cause = ex.getCause();
        if (cause instanceof GoogleJsonResponseException) {
            return toPhotoFrameException((GoogleJsonResponseException) cause);
        }
        return new PhotoFrameException(PhotoErrorCode.UNKNOWN, PhotoErrorCode.UNKNOWN.getDefaultMessage(), ex);
    }
}
