// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.api;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.api.client.http.HttpResponseException;

/**
 * Maps Google Photos Picker HTTP errors to user-facing {@link PhotoFrameException}s.
 */
public final class GooglePickerApiErrors {

    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final String PICKER_ENABLE_URL =
            "https://console.developers.google.com/apis/api/photospicker.googleapis.com/overview";

    private GooglePickerApiErrors() {
    }

    public static PhotoFrameException toPhotoFrameException(HttpResponseException ex) {
        int status = ex.getStatusCode();
        String detail = extractGoogleMessage(ex);
        if (detail.isEmpty()) {
            detail = ex.getStatusMessage() != null ? ex.getStatusMessage() : ("HTTP " + status);
        }

        if (status == 403) {
            if (detail.contains("disabled")
                    || detail.contains("not been used")
                    || detail.contains("accessNotConfigured")
                    || detail.contains("SERVICE_DISABLED")) {
                return new PhotoFrameException(
                        PhotoErrorCode.PICKER_SESSION_FAILED,
                        "Google Photos Picker API is not enabled for your Cloud project. "
                                + "Open Google Cloud Console → APIs → enable \"Google Photos Picker API\", "
                                + "wait a few minutes, then try again. "
                                + PICKER_ENABLE_URL,
                        ex);
            }
            if (detail.toLowerCase().contains("scope") || detail.contains("insufficient")) {
                return new PhotoFrameException(
                        PhotoErrorCode.AUTH_FAILED,
                        "OAuth scope missing. Re-authorize with: "
                                + "https://www.googleapis.com/auth/photospicker.mediaitems.readonly",
                        ex);
            }
            return new PhotoFrameException(PhotoErrorCode.PICKER_SESSION_FAILED, detail, ex);
        }
        if (status == 401) {
            return new PhotoFrameException(PhotoErrorCode.AUTH_FAILED, PhotoErrorCode.AUTH_FAILED.getDefaultMessage(), ex);
        }
        return new PhotoFrameException(
                PhotoErrorCode.GOOGLE_API_ERROR,
                PhotoErrorCode.GOOGLE_API_ERROR.getDefaultMessage() + " " + detail,
                ex);
    }

    private static String extractGoogleMessage(HttpResponseException ex) {
        String content = ex.getContent();
        if (content == null || content.isBlank()) {
            content = ex.getMessage();
        }
        if (content == null) {
            return "";
        }
        int jsonStart = content.indexOf('{');
        if (jsonStart >= 0) {
            content = content.substring(jsonStart);
        }
        try {
            JsonNode root = MAPPER.readTree(content);
            JsonNode message = root.path("error").path("message");
            if (message.isTextual()) {
                return message.asText();
            }
        } catch (Exception ignored) {
            // fall through
        }
        return content.length() > 300 ? content.substring(0, 300) + "…" : content;
    }
}
