// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.api;

/**
 * Application error with a stable code and user-facing message for the frontend.
 */
public class PhotoFrameException extends RuntimeException {

    public static final String API_PREFIX = "PHOTOFRAME_ERROR:";

    private final PhotoErrorCode code;

    public PhotoFrameException(PhotoErrorCode code) {
        super(code.getDefaultMessage());
        this.code = code;
    }

    public PhotoFrameException(PhotoErrorCode code, String message) {
        super(message);
        this.code = code;
    }

    public PhotoFrameException(PhotoErrorCode code, String message, Throwable cause) {
        super(message, cause);
        this.code = code;
    }

    public PhotoErrorCode getCode() {
        return code;
    }

    public String getUserMessage() {
        return getMessage();
    }

    /** Plain-text body for legacy slideshow (format=text). */
    public String toApiText() {
        return API_PREFIX + code.name() + ":" + getUserMessage();
    }
}
