// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.api;

/**
 * User-visible error codes returned to the slideshow and pick page.
 */
public enum PhotoErrorCode {

    AUTH_CONFIG("Google Photos credentials are missing or incomplete. Check google-photos-credentials.properties."),
    AUTH_FAILED("Google Photos authentication failed. Refresh the OAuth token with photospicker.mediaitems.readonly."),
    NO_IMAGES("0 images available for the slideshow. Choose photos from your Google Photos library."),
    PICKER_SESSION_FAILED("Failed to start Google Photos picker."),
    PICKER_NOT_READY("Photo selection not finished yet. Complete picking in Google Photos."),
    GOOGLE_API_ERROR("Google Photos API error."),
    LOCAL_FOLDER_MISSING("Local photo folder not found."),
    UNKNOWN("An unexpected error occurred.");

    private final String defaultMessage;

    PhotoErrorCode(String defaultMessage) {
        this.defaultMessage = defaultMessage;
    }

    public String getDefaultMessage() {
        return defaultMessage;
    }
}
