// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.api;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

import java.util.HashMap;
import java.util.Map;

public final class PhotoApiResponse {

    public static final String PICK_PAGE_PATH = "/myphotoframe.html";

    private PhotoApiResponse() {
    }

    public static ResponseEntity<?> error(PhotoFrameException ex, String format) {
        HttpStatus status = statusFor(ex.getCode());
        if (isPlainFormat(format)) {
            return ResponseEntity.status(status)
                    .contentType(MediaType.TEXT_PLAIN)
                    .body(ex.toApiText());
        }
        Map<String, Object> body = new HashMap<>();
        body.put("success", false);
        body.put("code", ex.getCode().name());
        body.put("error", ex.getUserMessage());
        body.put("pickUrl", PICK_PAGE_PATH);
        return ResponseEntity.status(status).body(body);
    }

    public static HttpStatus statusFor(PhotoErrorCode code) {
        return switch (code) {
            case AUTH_CONFIG, AUTH_FAILED -> HttpStatus.UNAUTHORIZED;
            case NO_IMAGES, PICKER_NOT_READY -> HttpStatus.SERVICE_UNAVAILABLE;
            case PICKER_SESSION_FAILED, GOOGLE_API_ERROR, LOCAL_FOLDER_MISSING, UNKNOWN ->
                    HttpStatus.INTERNAL_SERVER_ERROR;
        };
    }

    public static boolean isPlainFormat(String format) {
        return "text".equalsIgnoreCase(format) || "plain".equalsIgnoreCase(format);
    }
}
