// Generated by Auto (Composer) - 2026-05-25
// Model: Composer
package com.mwa.photoframe.source;

import com.mwa.photoframe.util.PhotoFrameTraceLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

/**
 * Loads Google Photos OAuth settings from a properties file.
 */
public class GooglePhotosCredentials {

    private static final Logger log = LoggerFactory.getLogger(GooglePhotosCredentials.class);

    public static final String KEY_CLIENT_ID = "google.photos.client.id";
    public static final String KEY_CLIENT_SECRET = "google.photos.client.secret";
    public static final String KEY_REFRESH_TOKEN = "google.photos.refresh.token";

    private final String clientId;
    private final String clientSecret;
    private final String refreshToken;

    public GooglePhotosCredentials(String clientId, String clientSecret, String refreshToken) {
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.refreshToken = refreshToken;
    }

    public static GooglePhotosCredentials fromEnvironment() {
        String clientId = trimEnv("GOOGLE_PHOTOS_CLIENT_ID");
        String clientSecret = trimEnv("GOOGLE_PHOTOS_CLIENT_SECRET");
        String refreshToken = trimEnv("GOOGLE_PHOTOS_REFRESH_TOKEN");
        if (clientId.isEmpty() || clientSecret.isEmpty() || refreshToken.isEmpty()) {
            return null;
        }
        log.debug("Google credentials loaded from environment variables");
        return new GooglePhotosCredentials(clientId, clientSecret, refreshToken);
    }

    public static GooglePhotosCredentials load(Path path) throws IOException {
        GooglePhotosCredentials fromEnv = fromEnvironment();
        if (fromEnv != null) {
            return fromEnv;
        }
        PhotoFrameTraceLog.tracePath(log, "credentials-load", path);
        Properties props = new Properties();
        if (!Files.isRegularFile(path)) {
            IOException ex = new IOException("Google Photos credentials file not found: " + path.toAbsolutePath());
            PhotoFrameTraceLog.logIoFailure(log, "credentials-load", path, ex);
            throw ex;
        }
        try (InputStream in = Files.newInputStream(path)) {
            props.load(in);
            PhotoFrameTraceLog.logRead(log, path, PhotoFrameTraceLog.fileSize(path));
        } catch (IOException ex) {
            PhotoFrameTraceLog.logIoFailure(log, "credentials-load", path, ex);
            throw ex;
        }
        String clientId = props.getProperty(KEY_CLIENT_ID, "").trim();
        String clientSecret = props.getProperty(KEY_CLIENT_SECRET, "").trim();
        String refreshToken = props.getProperty(KEY_REFRESH_TOKEN, "").trim();
        if (clientId.isEmpty() || clientSecret.isEmpty() || refreshToken.isEmpty()) {
            log.error("IO credentials-load invalid content path={} (missing required keys)", path.toAbsolutePath());
            throw new IOException(KEY_CLIENT_ID + ", " + KEY_CLIENT_SECRET + " and " + KEY_REFRESH_TOKEN
                    + " are required");
        }
        log.debug("IO credentials-load OK path={} clientId={}…", path.toAbsolutePath(),
                clientId.length() > 8 ? clientId.substring(0, 8) : clientId);
        return new GooglePhotosCredentials(clientId, clientSecret, refreshToken);
    }

    public String getClientId() {
        return clientId;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public String getRefreshToken() {
        return refreshToken;
    }

    private static String trimEnv(String name) {
        String value = System.getenv(name);
        return value != null ? value.trim() : "";
    }
}
