// Generated by Auto (Composer) - 2026-05-25
// Model: Composer
package com.mwa.photoframe.source;

import com.mwa.photoframe.util.PhotoFrameTraceLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Stream;

/**
 * Local JPEG cache for Google Photos media.
 */
public final class GooglePhotosImageCache {

    private static final Logger log = LoggerFactory.getLogger(GooglePhotosImageCache.class);

    private GooglePhotosImageCache() {
    }

    public static Path resolveCacheDir(Path configuredDir) throws IOException {
        PhotoFrameTraceLog.tracePath(log, "cache-resolve-dir", configuredDir);
        try {
            if (!Files.exists(configuredDir)) {
                Files.createDirectories(configuredDir);
                PhotoFrameTraceLog.logDirectoryCreated(log, configuredDir);
            }
            PhotoFrameTraceLog.logFreeSpace(log, "cache-dir", configuredDir);
            log.debug("IO cache-dir OK path={}", configuredDir.toAbsolutePath());
            return configuredDir;
        } catch (IOException ex) {
            PhotoFrameTraceLog.logIoFailure(log, "cache-resolve-dir", configuredDir, ex);
            throw ex;
        }
    }

    public static Path cacheFile(Path cacheDir, String mediaId) {
        return cacheDir.resolve(safeFileName(mediaId) + ".jpg");
    }

    public static boolean isCached(Path cacheDir, String mediaId) {
        Path file = cacheFile(cacheDir, mediaId);
        boolean exists = Files.isRegularFile(file);
        if (log.isTraceEnabled()) {
            log.trace("IO cache-hit id={} path={} cached={}", mediaId, file.toAbsolutePath(), exists);
        }
        return exists;
    }

    public static void saveJpeg(Path cacheDir, String mediaId, byte[] jpegBytes) throws IOException {
        Path file = cacheFile(cacheDir, mediaId);
        PhotoFrameTraceLog.tracePath(log, "cache-write", file);
        try {
            Path parent = file.getParent();
            if (parent != null && !Files.exists(parent)) {
                Files.createDirectories(parent);
                PhotoFrameTraceLog.logDirectoryCreated(log, parent);
            }
            Files.write(file, jpegBytes);
            PhotoFrameTraceLog.logWrite(log, file, jpegBytes.length);
            log.debug("IO cache-write OK id={} path={} bytes={}", mediaId, file.toAbsolutePath(), jpegBytes.length);
        } catch (IOException ex) {
            PhotoFrameTraceLog.logIoFailure(log, "cache-write", file, ex);
            throw ex;
        }
    }

    public static void delete(Path cacheDir, String mediaId) throws IOException {
        Path file = cacheFile(cacheDir, mediaId);
        PhotoFrameTraceLog.tracePath(log, "cache-delete", file);
        try {
            boolean deleted = Files.deleteIfExists(file);
            log.debug("IO cache-delete path={} deleted={}", file.toAbsolutePath(), deleted);
        } catch (IOException ex) {
            PhotoFrameTraceLog.logIoFailure(log, "cache-delete", file, ex);
            throw ex;
        }
    }

    public static void clearAll(Path cacheDir) throws IOException {
        PhotoFrameTraceLog.tracePath(log, "cache-clear-all", cacheDir);
        if (!Files.isDirectory(cacheDir)) {
            return;
        }
        try (Stream<Path> stream = Files.list(cacheDir)) {
            int removed = 0;
            for (Path p : (Iterable<Path>) stream::iterator) {
                if (Files.isRegularFile(p)) {
                    Files.deleteIfExists(p);
                    removed++;
                }
            }
            log.debug("IO cache-clear-all OK path={} filesRemoved={}", cacheDir.toAbsolutePath(), removed);
        } catch (IOException ex) {
            PhotoFrameTraceLog.logIoFailure(log, "cache-clear-all", cacheDir, ex);
            throw ex;
        }
    }

    private static String safeFileName(String mediaId) {
        return mediaId.replaceAll("[^a-zA-Z0-9._-]", "_");
    }
}
