// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.source;

import com.google.api.client.googleapis.auth.oauth2.GoogleCredential;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Slideshow catalog from photos chosen with the Google Photos Picker API.
 */
public class GooglePhotosPickedPhotoSource implements PhotoSource, GooglePhotosCredentialProvider {

    private static final Logger log = LoggerFactory.getLogger(GooglePhotosPickedPhotoSource.class);

    private final GooglePhotosCredentials credentials;
    private final Path pickedFile;
    private GoogleCredential googleCredential;

    public GooglePhotosPickedPhotoSource(GooglePhotosCredentials credentials, Path pickedFile) {
        this.credentials = credentials;
        this.pickedFile = pickedFile;
    }

    @Override
    public String getType() {
        return "google";
    }

    @Override
    public List<PhotoEntry> loadCatalog() throws Exception {
        log.debug("Google picked catalog load path={}", pickedFile.toAbsolutePath());
        List<GooglePhotosPickedStore.StoredPickedItem> stored = GooglePhotosPickedStore.load(pickedFile);
        List<PhotoEntry> entries = new ArrayList<>();
        for (GooglePhotosPickedStore.StoredPickedItem item : stored) {
            if (item.id == null || item.baseUrl == null) {
                continue;
            }
            String mime = item.mimeType != null ? item.mimeType : "image/jpeg";
            entries.add(PhotoEntry.google(item.id, item.baseUrl, mime));
        }
        log.info("Loaded {} picked Google Photos", entries.size());
        return Collections.unmodifiableList(entries);
    }

    @Override
    public synchronized GoogleCredential getCredential() throws Exception {
        if (googleCredential == null) {
            log.debug("Google OAuth credential lazy init");
            googleCredential = GooglePhotosClientFactory.buildCredential(credentials);
        }
        return googleCredential;
    }
}
