// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.source;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

/**
 * Loads Google Photos OAuth settings from a properties file.
 */
public class GooglePhotosCredentials {

    public static final String KEY_CLIENT_ID = "google.photos.client.id";
    public static final String KEY_CLIENT_SECRET = "google.photos.client.secret";
    public static final String KEY_REFRESH_TOKEN = "google.photos.refresh.token";

    private final String clientId;
    private final String clientSecret;
    private final String refreshToken;

    public GooglePhotosCredentials(String clientId, String clientSecret, String refreshToken) {
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.refreshToken = refreshToken;
    }

    public static GooglePhotosCredentials load(Path path) throws IOException {
        Properties props = new Properties();
        if (!Files.isRegularFile(path)) {
            throw new IOException("Google Photos credentials file not found: " + path.toAbsolutePath());
        }
        try (InputStream in = Files.newInputStream(path)) {
            props.load(in);
        }
        String clientId = props.getProperty(KEY_CLIENT_ID, "").trim();
        String clientSecret = props.getProperty(KEY_CLIENT_SECRET, "").trim();
        String refreshToken = props.getProperty(KEY_REFRESH_TOKEN, "").trim();
        if (clientId.isEmpty() || clientSecret.isEmpty() || refreshToken.isEmpty()) {
            throw new IOException(KEY_CLIENT_ID + ", " + KEY_CLIENT_SECRET + " and " + KEY_REFRESH_TOKEN
                    + " are required");
        }
        return new GooglePhotosCredentials(clientId, clientSecret, refreshToken);
    }

    public String getClientId() {
        return clientId;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public String getRefreshToken() {
        return refreshToken;
    }
}
