// Generated by Auto (Composer) - 2026-05-22
// Model: Composer
package com.mwa.photoframe.source;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * On-disk JPEG cache for picked Google Photos (avoids expired Google baseUrl links).
 */
public final class GooglePhotosImageCache {

    private GooglePhotosImageCache() {
    }

    public static Path resolveCacheDir(Path configuredDir) throws IOException {
        if (!Files.exists(configuredDir)) {
            Files.createDirectories(configuredDir);
        }
        return configuredDir;
    }

    public static Path cacheFile(Path cacheDir, String mediaId) {
        return cacheDir.resolve(safeFileName(mediaId) + ".jpg");
    }

    public static boolean isCached(Path cacheDir, String mediaId) {
        return Files.isRegularFile(cacheFile(cacheDir, mediaId));
    }

    public static void saveJpeg(Path cacheDir, String mediaId, byte[] jpegBytes) throws IOException {
        Path file = cacheFile(cacheDir, mediaId);
        Path parent = file.getParent();
        if (parent != null && !Files.exists(parent)) {
            Files.createDirectories(parent);
        }
        Files.write(file, jpegBytes);
    }

    public static void delete(Path cacheDir, String mediaId) throws IOException {
        Files.deleteIfExists(cacheFile(cacheDir, mediaId));
    }

    public static void clearAll(Path cacheDir) throws IOException {
        if (!Files.isDirectory(cacheDir)) {
            return;
        }
        try (var stream = Files.list(cacheDir)) {
            for (Path p : stream.toList()) {
                if (Files.isRegularFile(p)) {
                    Files.deleteIfExists(p);
                }
            }
        }
    }

    private static String safeFileName(String mediaId) {
        StringBuilder sb = new StringBuilder(mediaId.length());
        for (int i = 0; i < mediaId.length(); i++) {
            char c = mediaId.charAt(i);
            if ((c >= 'a' && c <= 'z')
                    || (c >= 'A' && c <= 'Z')
                    || (c >= '0' && c <= '9')
                    || c == '-' || c == '_') {
                sb.append(c);
            } else {
                sb.append('_');
            }
        }
        return sb.toString();
    }
}
