// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.source;

import com.google.api.client.googleapis.auth.oauth2.GoogleCredential;
import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.jackson2.JacksonFactory;
import com.mwa.photoframe.api.PhotoErrorCode;
import com.mwa.photoframe.api.PhotoFrameException;

import java.util.Collections;
import java.util.List;

public final class GooglePhotosClientFactory {

    private static final List<String> PICKER_SCOPES = Collections.singletonList(
            "https://www.googleapis.com/auth/photospicker.mediaitems.readonly");

    private GooglePhotosClientFactory() {
    }

    public static GoogleCredential buildCredential(GooglePhotosCredentials creds) throws Exception {
        try {
            NetHttpTransport transport = GoogleNetHttpTransport.newTrustedTransport();
            GoogleCredential credential = new GoogleCredential.Builder()
                    .setTransport(transport)
                    .setJsonFactory(JacksonFactory.getDefaultInstance())
                    .setClientSecrets(creds.getClientId(), creds.getClientSecret())
                    .build()
                    .setRefreshToken(creds.getRefreshToken())
                    .createScoped(PICKER_SCOPES);
            credential.refreshToken();
            return credential;
        } catch (Exception ex) {
            if (isAuthFailure(ex)) {
                throw new PhotoFrameException(
                        PhotoErrorCode.AUTH_FAILED,
                        PhotoErrorCode.AUTH_FAILED.getDefaultMessage(),
                        ex);
            }
            throw ex;
        }
    }

    private static boolean isAuthFailure(Throwable ex) {
        Throwable t = ex;
        while (t != null) {
            String name = t.getClass().getName();
            if (name.contains("TokenResponseException")) {
                return true;
            }
            t = t.getCause();
        }
        return false;
    }
}
