// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.source;

import com.google.api.client.googleapis.auth.oauth2.GoogleCredential;

/**
 * Supplies OAuth credentials for fetching Google / Picker media base URLs.
 */
public interface GooglePhotosCredentialProvider {

    GoogleCredential getCredential() throws Exception;
}
