// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.source;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Persists photos chosen via the Google Photos Picker API.
 */
public final class GooglePhotosPickedStore {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private GooglePhotosPickedStore() {
    }

    public static boolean hasItems(Path path) throws IOException {
        return !load(path).isEmpty();
    }

    public static List<StoredPickedItem> load(Path path) throws IOException {
        if (!Files.isRegularFile(path)) {
            return Collections.emptyList();
        }
        String json = Files.readString(path);
        if (json.isBlank()) {
            return Collections.emptyList();
        }
        PickedCatalog catalog = MAPPER.readValue(json, PickedCatalog.class);
        if (catalog.items == null) {
            return Collections.emptyList();
        }
        return Collections.unmodifiableList(new ArrayList<>(catalog.items));
    }

    public static void save(Path path, List<StoredPickedItem> items) throws IOException {
        Path parent = path.getParent();
        if (parent != null && !Files.exists(parent)) {
            Files.createDirectories(parent);
        }
        PickedCatalog catalog = new PickedCatalog();
        catalog.updatedAt = Instant.now().toString();
        catalog.items = items;
        MAPPER.writerWithDefaultPrettyPrinter().writeValue(path.toFile(), catalog);
    }

    public static int count(Path path) throws IOException {
        return load(path).size();
    }

    /** Merges new items into existing selection by id (adds new, updates metadata for duplicates). */
    public static int merge(Path path, List<StoredPickedItem> incoming) throws IOException {
        Map<String, StoredPickedItem> byId = new LinkedHashMap<>();
        for (StoredPickedItem item : load(path)) {
            if (item.id != null && !item.id.isEmpty()) {
                byId.put(item.id, item);
            }
        }
        int added = 0;
        for (StoredPickedItem item : incoming) {
            if (item.id == null || item.id.isEmpty()) {
                continue;
            }
            if (!byId.containsKey(item.id)) {
                added++;
            }
            byId.put(item.id, item);
        }
        save(path, new ArrayList<>(byId.values()));
        return added;
    }

    public static boolean removeById(Path path, String id) throws IOException {
        List<StoredPickedItem> items = new ArrayList<>(load(path));
        boolean removed = items.removeIf(item -> id.equals(item.id));
        if (removed) {
            save(path, items);
        }
        return removed;
    }

    public static void clear(Path path) throws IOException {
        save(path, Collections.emptyList());
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class PickedCatalog {
        public String updatedAt;
        public List<StoredPickedItem> items = Collections.emptyList();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class StoredPickedItem {
        public String id;
        public String baseUrl;
        public String mimeType;
        public String filename;
    }
}
