// Generated by Auto (Composer) - 2026-05-25
// Model: Composer
package com.mwa.photoframe.source;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mwa.photoframe.util.PhotoFrameTraceLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Persists photos chosen via the Google Photos Picker API.
 */
public final class GooglePhotosPickedStore {

    private static final Logger log = LoggerFactory.getLogger(GooglePhotosPickedStore.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private GooglePhotosPickedStore() {
    }

    public static boolean hasItems(Path path) throws IOException {
        PhotoFrameTraceLog.tracePath(log, "picked-hasItems", path);
        return !load(path).isEmpty();
    }

    public static List<StoredPickedItem> load(Path path) throws IOException {
        PhotoFrameTraceLog.tracePath(log, "picked-load", path);
        if (!Files.isRegularFile(path)) {
            log.debug("IO picked-load missing file path={}", path.toAbsolutePath());
            return Collections.emptyList();
        }
        try {
            String json = Files.readString(path);
            if (json.isBlank()) {
                log.debug("IO picked-load empty file path={}", path.toAbsolutePath());
                return Collections.emptyList();
            }
            PickedCatalog catalog = MAPPER.readValue(json, PickedCatalog.class);
            if (catalog.items == null) {
                return Collections.emptyList();
            }
            List<StoredPickedItem> items = Collections.unmodifiableList(new ArrayList<>(catalog.items));
            PhotoFrameTraceLog.logRead(log, path, json.length());
            log.debug("IO picked-load OK path={} items={}", path.toAbsolutePath(), items.size());
            return items;
        } catch (IOException ex) {
            PhotoFrameTraceLog.logIoFailure(log, "picked-load", path, ex);
            throw ex;
        }
    }

    public static void save(Path path, List<StoredPickedItem> items) throws IOException {
        PhotoFrameTraceLog.tracePath(log, "picked-save", path);
        try {
            Path parent = path.getParent();
            if (parent != null && !Files.exists(parent)) {
                Files.createDirectories(parent);
                PhotoFrameTraceLog.logDirectoryCreated(log, parent);
            }
            PickedCatalog catalog = new PickedCatalog();
            catalog.updatedAt = Instant.now().toString();
            catalog.items = items;
            MAPPER.writerWithDefaultPrettyPrinter().writeValue(path.toFile(), catalog);
            PhotoFrameTraceLog.logWrite(log, path, PhotoFrameTraceLog.fileSize(path));
            log.debug("IO picked-save OK path={} items={}", path.toAbsolutePath(), items.size());
        } catch (IOException ex) {
            PhotoFrameTraceLog.logIoFailure(log, "picked-save", path, ex);
            throw ex;
        }
    }

    public static int count(Path path) throws IOException {
        return load(path).size();
    }

    public static int merge(Path path, List<StoredPickedItem> incoming) throws IOException {
        log.debug("IO picked-merge path={} incoming={}", path.toAbsolutePath(), incoming.size());
        Map<String, StoredPickedItem> byId = new LinkedHashMap<>();
        for (StoredPickedItem item : load(path)) {
            if (item.id != null && !item.id.isEmpty()) {
                byId.put(item.id, item);
            }
        }
        int added = 0;
        for (StoredPickedItem item : incoming) {
            if (item.id == null || item.id.isEmpty()) {
                continue;
            }
            if (!byId.containsKey(item.id)) {
                added++;
            }
            byId.put(item.id, item);
        }
        save(path, new ArrayList<>(byId.values()));
        log.debug("IO picked-merge OK path={} added={} total={}", path.toAbsolutePath(), added, byId.size());
        return added;
    }

    public static StoredPickedItem findById(Path path, String id) throws IOException {
        for (StoredPickedItem item : load(path)) {
            if (id.equals(item.id)) {
                return item;
            }
        }
        return null;
    }

    public static boolean removeById(Path path, String id) throws IOException {
        log.debug("IO picked-remove path={} id={}", path.toAbsolutePath(), id);
        List<StoredPickedItem> items = new ArrayList<>(load(path));
        boolean removed = items.removeIf(item -> id.equals(item.id));
        if (removed) {
            save(path, items);
        }
        return removed;
    }

    public static void clear(Path path) throws IOException {
        log.debug("IO picked-clear path={}", path.toAbsolutePath());
        save(path, Collections.emptyList());
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class PickedCatalog {
        public String updatedAt;
        public List<StoredPickedItem> items = Collections.emptyList();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class StoredPickedItem {
        public String id;
        public String baseUrl;
        public String mimeType;
        public String filename;
    }
}
