// Generated by Auto (Composer) - 2026-05-22
package com.mwa.photoframe.source;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.concurrent.TimeUnit;

/**
 * Converts HEIC/HEIF to JPEG using macOS {@code sips} when available.
 */
public final class HeicImageConverter {

    private static final Logger log = LoggerFactory.getLogger(HeicImageConverter.class);
    private static final long SIPS_TIMEOUT_SECONDS = 60;

    private HeicImageConverter() {
    }

    public static boolean isHeicPath(Path path) {
        String name = path.getFileName().toString().toLowerCase(Locale.ROOT);
        return name.endsWith(".heic") || name.endsWith(".heif");
    }

    public static boolean isHeicMime(String mime) {
        if (mime == null) {
            return false;
        }
        String m = mime.toLowerCase(Locale.ROOT);
        return m.contains("heic") || m.contains("heif");
    }

    public static byte[] toJpeg(byte[] heicBytes) throws IOException {
        Path tmpIn = Files.createTempFile("photoframe-heic-in-", ".heic");
        try {
            Files.write(tmpIn, heicBytes);
            return toJpeg(tmpIn);
        } finally {
            Files.deleteIfExists(tmpIn);
        }
    }

    public static byte[] toJpeg(Path heicFile) throws IOException {
        Path tmp = Files.createTempFile("photoframe-heic-", ".jpg");
        try {
            ProcessBuilder pb = new ProcessBuilder(
                    "sips",
                    "-s", "format", "jpeg",
                    heicFile.toAbsolutePath().toString(),
                    "--out", tmp.toAbsolutePath().toString());
            pb.redirectErrorStream(true);
            Process process = pb.start();
            String output = readProcessOutput(process);
            boolean finished;
            try {
                finished = process.waitFor(SIPS_TIMEOUT_SECONDS, TimeUnit.SECONDS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                process.destroyForcibly();
                throw new IOException("HEIC conversion interrupted", e);
            }
            if (!finished) {
                process.destroyForcibly();
                throw new IOException("HEIC conversion timed out for " + heicFile.getFileName());
            }
            if (process.exitValue() != 0) {
                throw new IOException("sips failed (exit " + process.exitValue() + ") for "
                        + heicFile.getFileName() + ": " + output);
            }
            if (!Files.isRegularFile(tmp) || Files.size(tmp) == 0) {
                throw new IOException("HEIC conversion produced no output for " + heicFile.getFileName());
            }
            byte[] jpeg = Files.readAllBytes(tmp);
            log.debug("Converted {} to JPEG ({} bytes)", heicFile.getFileName(), jpeg.length);
            return jpeg;
        } finally {
            Files.deleteIfExists(tmp);
        }
    }

    private static String readProcessOutput(Process process) throws IOException {
        try (InputStream in = process.getInputStream()) {
            return new String(in.readAllBytes(), StandardCharsets.UTF_8).trim();
        }
    }
}
