// Generated by Auto (Composer) - 2026-05-22
// HEIC conversion via Openize HEIC (pure Java, no macOS sips)
package com.mwa.photoframe.source;

import openize.heic.decoder.HeicImage;
import openize.heic.decoder.PixelFormat;
import openize.io.IOFileStream;
import openize.io.IOMode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;

/**
 * Converts HEIC/HEIF to JPEG using the Openize HEIC decoder (pure Java).
 */
public final class HeicImageConverter {

    private static final Logger log = LoggerFactory.getLogger(HeicImageConverter.class);

    private HeicImageConverter() {
    }

    public static boolean isHeicPath(Path path) {
        String name = path.getFileName().toString().toLowerCase(Locale.ROOT);
        return name.endsWith(".heic") || name.endsWith(".heif");
    }

    public static boolean isHeicMime(String mime) {
        if (mime == null) {
            return false;
        }
        String m = mime.toLowerCase(Locale.ROOT);
        return m.contains("heic") || m.contains("heif");
    }

    public static boolean isJpegBytes(byte[] bytes) {
        return bytes != null && bytes.length >= 3
                && (bytes[0] & 0xFF) == 0xFF
                && (bytes[1] & 0xFF) == 0xD8
                && (bytes[2] & 0xFF) == 0xFF;
    }

    public static boolean isPngBytes(byte[] bytes) {
        return bytes != null && bytes.length >= 8
                && bytes[0] == (byte) 0x89
                && bytes[1] == 'P'
                && bytes[2] == 'N'
                && bytes[3] == 'G';
    }

    /** Normalize downloaded bytes to JPEG for the local cache. */
    public static byte[] toCacheJpeg(byte[] bytes, String mime, String label) throws IOException {
        if (bytes == null || bytes.length == 0) {
            throw new IOException("Empty image data for " + safeLabel(label));
        }
        if (isJpegBytes(bytes)) {
            return bytes;
        }
        if (isPngBytes(bytes)) {
            return rasterToJpeg(ImageIO.read(new java.io.ByteArrayInputStream(bytes)), safeLabel(label));
        }
        if (isHeicMime(mime)) {
            return toJpeg(bytes);
        }
        try {
            return rasterToJpeg(ImageIO.read(new java.io.ByteArrayInputStream(bytes)), safeLabel(label));
        } catch (Exception ex) {
            throw new IOException("Unsupported image format for " + safeLabel(label) + ": " + ex.getMessage(), ex);
        }
    }

    private static byte[] rasterToJpeg(BufferedImage image, String label) throws IOException {
        if (image == null) {
            throw new IOException("Could not decode image for " + label);
        }
        BufferedImage rgb = image;
        if (image.getType() != BufferedImage.TYPE_INT_RGB) {
            rgb = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_RGB);
            rgb.getGraphics().drawImage(image, 0, 0, null);
        }
        ByteArrayOutputStream out = new ByteArrayOutputStream(Math.max(8192, image.getWidth() * image.getHeight() / 4));
        if (!ImageIO.write(rgb, "jpg", out)) {
            throw new IOException("JPEG ImageWriter not available");
        }
        return out.toByteArray();
    }

    private static String safeLabel(String label) {
        return label != null && !label.isEmpty() ? label : "photo";
    }

    public static byte[] toJpeg(byte[] heicBytes) throws IOException {
        Path tmpIn = Files.createTempFile("photoframe-heic-in-", ".heic");
        try {
            Files.write(tmpIn, heicBytes);
            return toJpeg(tmpIn);
        } finally {
            Files.deleteIfExists(tmpIn);
        }
    }

    public static byte[] toJpeg(Path heicFile) throws IOException {
        try (IOFileStream fs = new IOFileStream(heicFile.toAbsolutePath().toString(), IOMode.READ)) {
            HeicImage image = HeicImage.load(fs);
            int width = (int) image.getWidth();
            int height = (int) image.getHeight();
            if (width <= 0 || height <= 0) {
                throw new IOException("Invalid HEIC dimensions for " + heicFile.getFileName());
            }
            int[] pixels = image.getInt32Array(PixelFormat.Argb32);
            if (pixels == null || pixels.length < width * height) {
                throw new IOException("HEIC frame has no pixel data for " + heicFile.getFileName());
            }
            BufferedImage buffered = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
            buffered.setRGB(0, 0, width, height, pixels, 0, width);
            ByteArrayOutputStream out = new ByteArrayOutputStream(Math.max(8192, width * height / 4));
            if (!ImageIO.write(buffered, "jpg", out)) {
                throw new IOException("JPEG ImageWriter not available");
            }
            byte[] jpeg = out.toByteArray();
            log.debug("Converted {} to JPEG ({} bytes)", heicFile.getFileName(), jpeg.length);
            return jpeg;
        } catch (IOException e) {
            throw e;
        } catch (Exception e) {
            throw new IOException("HEIC conversion failed for " + heicFile.getFileName() + ": " + e.getMessage(), e);
        }
    }
}
