// Generated by Auto (Composer) - 2026-05-21
package com.mwa.photoframe.source;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;

public class LocalFolderPhotoSource implements PhotoSource {

    private static final Logger log = LoggerFactory.getLogger(LocalFolderPhotoSource.class);

    private static final String[] EXTENSIONS = {
            ".jpg", ".jpeg", ".png", ".gif", ".webp", ".bmp", ".heic", ".heif"
    };

    private final Path folder;

    public LocalFolderPhotoSource(Path folder) {
        this.folder = folder;
    }

    @Override
    public String getType() {
        return "local";
    }

    @Override
    public List<PhotoEntry> loadCatalog() throws Exception {
        if (!Files.isDirectory(folder)) {
            throw new IOException("Local photo folder does not exist: " + folder.toAbsolutePath());
        }
        List<String> names = new ArrayList<>();
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(folder)) {
            for (Path p : stream) {
                if (Files.isRegularFile(p) && isImageFile(p.getFileName().toString())) {
                    names.add(p.getFileName().toString());
                }
            }
        }
        names.sort(Comparator.naturalOrder());
        List<PhotoEntry> entries = new ArrayList<>();
        for (int i = 0; i < names.size(); i++) {
            String name = names.get(i);
            entries.add(PhotoEntry.local(String.valueOf(i), name, guessMimeType(name)));
        }
        log.info("Loaded {} local photos from {}", entries.size(), folder.toAbsolutePath());
        return entries;
    }

    public Path resolveFile(PhotoEntry entry) {
        return folder.resolve(entry.getLocalFileName());
    }

    private static boolean isImageFile(String name) {
        String lower = name.toLowerCase(Locale.ROOT);
        for (String ext : EXTENSIONS) {
            if (lower.endsWith(ext)) {
                return true;
            }
        }
        return false;
    }

    private static String guessMimeType(String name) {
        String lower = name.toLowerCase(Locale.ROOT);
        if (lower.endsWith(".png")) {
            return "image/png";
        }
        if (lower.endsWith(".gif")) {
            return "image/gif";
        }
        if (lower.endsWith(".webp")) {
            return "image/webp";
        }
        if (lower.endsWith(".bmp")) {
            return "image/bmp";
        }
        if (lower.endsWith(".heic")) {
            return "image/heic";
        }
        if (lower.endsWith(".heif")) {
            return "image/heif";
        }
        return "image/jpeg";
    }
}
