// Generated by Auto (Composer) - 2026-05-21
package com.mwa.photoframe.source;

import java.util.List;

public interface PhotoSource {

    String getType();

    List<PhotoEntry> loadCatalog() throws Exception;
}
