// Generated by Auto (Composer) - 2026-05-21
package com.mwa.photoframe.source;

/**
 * One photo in the slideshow catalog.
 */
public class PhotoEntry {

    private final String id;
    private final String sourceType;
    private final String mimeType;
    private final String localFileName;
    private final String googleBaseUrl;

    public PhotoEntry(String id, String sourceType, String mimeType, String localFileName, String googleBaseUrl) {
        this.id = id;
        this.sourceType = sourceType;
        this.mimeType = mimeType;
        this.localFileName = localFileName;
        this.googleBaseUrl = googleBaseUrl;
    }

    public static PhotoEntry local(String id, String fileName, String mimeType) {
        return new PhotoEntry(id, "local", mimeType, fileName, null);
    }

    public static PhotoEntry google(String mediaItemId, String baseUrl, String mimeType) {
        return new PhotoEntry(mediaItemId, "google", mimeType, null, baseUrl);
    }

    public String getId() {
        return id;
    }

    public String getSourceType() {
        return sourceType;
    }

    public String getMimeType() {
        return mimeType;
    }

    public String getLocalFileName() {
        return localFileName;
    }

    public String getGoogleBaseUrl() {
        return googleBaseUrl;
    }

    public boolean isLocal() {
        return "local".equalsIgnoreCase(sourceType);
    }

    public boolean isGoogle() {
        return "google".equalsIgnoreCase(sourceType);
    }
}
