// Generated by Auto (Composer) - 2026-05-22
// Model: Composer
package com.mwa.photoframe.source;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Persists slideshow layout (width, height, x, y in pixels only).
 */
public final class SlideshowDisplaySettingsStore {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private SlideshowDisplaySettingsStore() {
    }

    public static SlideshowDisplaySettings load(Path path, int defaultIntervalSeconds) throws IOException {
        if (!Files.isRegularFile(path)) {
            return SlideshowDisplaySettings.defaults(defaultIntervalSeconds);
        }
        String json = Files.readString(path);
        if (json.isBlank()) {
            return SlideshowDisplaySettings.defaults(defaultIntervalSeconds);
        }
        StoredSettings stored = MAPPER.readValue(json, StoredSettings.class);
        return SlideshowDisplaySettings.fromStored(stored, defaultIntervalSeconds);
    }

    public static SlideshowDisplaySettings save(Path path, SlideshowDisplaySettings settings) throws IOException {
        Path parent = path.getParent();
        if (parent != null && !Files.exists(parent)) {
            Files.createDirectories(parent);
        }
        SlideshowDisplaySettings normalized = settings.normalized();
        StoredSettings stored = new StoredSettings();
        stored.width = normalized.getWidth();
        stored.height = normalized.getHeight();
        stored.x = normalized.getX();
        stored.y = normalized.getY();
        stored.intervalSeconds = normalized.getIntervalSeconds();
        stored.showDisplayZone = normalized.isShowDisplayZone();
        stored.unit = normalized.getUnit();
        MAPPER.writerWithDefaultPrettyPrinter().writeValue(path.toFile(), stored);
        return normalized;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class StoredSettings {
        public double width = 0;
        public double height = 0;
        public double x = 0;
        public double y = 0;
        public int intervalSeconds = 0;
        public boolean showDisplayZone = false;
        public String unit = SlideshowDisplaySettings.UNIT_PIXELS;
    }
}
