// Generated by Auto (Composer) - 2026-05-22
// Model: Composer
package com.mwa.photoframe.source;

import java.util.LinkedHashMap;
import java.util.Map;

public class SlideshowDisplaySettings {

    public static final String UNIT_PIXELS = "px";
    public static final int MIN_INTERVAL_SECONDS = 1;
    public static final int MAX_INTERVAL_SECONDS = 86400;

    private final double width;
    private final double height;
    private final double x;
    private final double y;
    private final int intervalSeconds;
    private final boolean showDisplayZone;
    private final String unit;

    public SlideshowDisplaySettings(
            double width,
            double height,
            double x,
            double y,
            int intervalSeconds,
            boolean showDisplayZone,
            String unit) {
        this.width = width;
        this.height = height;
        this.x = x;
        this.y = y;
        this.intervalSeconds = intervalSeconds;
        this.showDisplayZone = showDisplayZone;
        this.unit = unit != null && !unit.isBlank() ? unit.trim() : UNIT_PIXELS;
    }

    public static SlideshowDisplaySettings defaults(int defaultIntervalSeconds) {
        return new SlideshowDisplaySettings(0, 0, 0, 0, defaultIntervalSeconds, false, UNIT_PIXELS);
    }

    public static SlideshowDisplaySettings fromStored(
            SlideshowDisplaySettingsStore.StoredSettings stored, int defaultIntervalSeconds) {
        if (stored == null) {
            return defaults(defaultIntervalSeconds);
        }
        int interval = stored.intervalSeconds > 0 ? stored.intervalSeconds : defaultIntervalSeconds;
        return new SlideshowDisplaySettings(
                        stored.width,
                        stored.height,
                        stored.x,
                        stored.y,
                        interval,
                        stored.showDisplayZone,
                        stored.unit)
                .normalized();
    }

    public static SlideshowDisplaySettings fromMap(Map<String, Object> body, int defaultIntervalSeconds) {
        if (body == null) {
            return defaults(defaultIntervalSeconds);
        }
        Object unitValue = body.get("unit");
        String unit = unitValue != null ? String.valueOf(unitValue) : UNIT_PIXELS;
        int interval = toInt(body.get("intervalSeconds"), defaultIntervalSeconds);
        if (interval <= 0) {
            interval = toInt(body.get("interval"), defaultIntervalSeconds);
        }
        return new SlideshowDisplaySettings(
                        toDouble(body.get("width"), 0),
                        toDouble(body.get("height"), 0),
                        toDouble(body.get("x"), 0),
                        toDouble(body.get("y"), 0),
                        interval,
                        toBoolean(body.get("showDisplayZone"), false),
                        unit)
                .normalized();
    }

    public SlideshowDisplaySettings normalized() {
        return new SlideshowDisplaySettings(
                clampSize(width, 0),
                clampSize(height, 0),
                clampPosition(x, 0),
                clampPosition(y, 0),
                clampInterval(intervalSeconds, MIN_INTERVAL_SECONDS),
                showDisplayZone,
                UNIT_PIXELS);
    }

    public double getWidth() {
        return width;
    }

    public double getHeight() {
        return height;
    }

    public double getX() {
        return x;
    }

    public double getY() {
        return y;
    }

    public int getIntervalSeconds() {
        return intervalSeconds;
    }

    public String getUnit() {
        return unit;
    }

    public boolean isShowDisplayZone() {
        return showDisplayZone;
    }

    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("success", true);
        map.put("width", width);
        map.put("height", height);
        map.put("x", x);
        map.put("y", y);
        map.put("intervalSeconds", intervalSeconds);
        map.put("showDisplayZone", showDisplayZone);
        map.put("unit", UNIT_PIXELS);
        return map;
    }

    private static boolean toBoolean(Object value, boolean fallback) {
        if (value == null) {
            return fallback;
        }
        if (value instanceof Boolean) {
            return (Boolean) value;
        }
        String text = String.valueOf(value).trim();
        if ("true".equalsIgnoreCase(text) || "1".equals(text) || "yes".equalsIgnoreCase(text)) {
            return true;
        }
        if ("false".equalsIgnoreCase(text) || "0".equals(text) || "no".equalsIgnoreCase(text)) {
            return false;
        }
        return fallback;
    }

    private static double toDouble(Object value, double fallback) {
        if (value == null) {
            return fallback;
        }
        if (value instanceof Number) {
            return ((Number) value).doubleValue();
        }
        try {
            return Double.parseDouble(String.valueOf(value).trim());
        } catch (NumberFormatException ex) {
            return fallback;
        }
    }

    private static int toInt(Object value, int fallback) {
        if (value == null) {
            return fallback;
        }
        if (value instanceof Number) {
            return ((Number) value).intValue();
        }
        try {
            return Integer.parseInt(String.valueOf(value).trim());
        } catch (NumberFormatException ex) {
            return fallback;
        }
    }

    private static int clampInterval(int value, int fallback) {
        if (value < MIN_INTERVAL_SECONDS) {
            return fallback < MIN_INTERVAL_SECONDS ? MIN_INTERVAL_SECONDS : fallback;
        }
        if (value > MAX_INTERVAL_SECONDS) {
            return MAX_INTERVAL_SECONDS;
        }
        return value;
    }

    private static double clampSize(double value, double fallback) {
        if (Double.isNaN(value) || Double.isInfinite(value)) {
            return fallback;
        }
        if (value < 0) {
            return 0;
        }
        if (value > 32_000) {
            return 32_000;
        }
        return Math.round(value);
    }

    private static double clampPosition(double value, double fallback) {
        if (Double.isNaN(value) || Double.isInfinite(value)) {
            return fallback;
        }
        if (value < 0) {
            return 0;
        }
        if (value > 32_000) {
            return 32_000;
        }
        return Math.round(value);
    }
}
