// Generated by Auto (Composer) - 2026-05-25
// Model: Composer
package com.mwa.photoframe.source;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mwa.photoframe.util.PhotoFrameTraceLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Persists slideshow layout (width, height, x, y in pixels only).
 */
public final class SlideshowDisplaySettingsStore {

    private static final Logger log = LoggerFactory.getLogger(SlideshowDisplaySettingsStore.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private SlideshowDisplaySettingsStore() {
    }

    public static SlideshowDisplaySettings load(Path path, int defaultIntervalSeconds) throws IOException {
        PhotoFrameTraceLog.tracePath(log, "display-settings-load", path);
        if (!Files.isRegularFile(path)) {
            log.debug("IO display-settings-load missing file path={} — using defaults", path.toAbsolutePath());
            return SlideshowDisplaySettings.defaults(defaultIntervalSeconds);
        }
        try {
            String json = Files.readString(path);
            if (json.isBlank()) {
                log.debug("IO display-settings-load empty path={}", path.toAbsolutePath());
                return SlideshowDisplaySettings.defaults(defaultIntervalSeconds);
            }
            StoredSettings stored = MAPPER.readValue(json, StoredSettings.class);
            PhotoFrameTraceLog.logRead(log, path, json.length());
            log.debug("IO display-settings-load OK path={}", path.toAbsolutePath());
            return SlideshowDisplaySettings.fromStored(stored, defaultIntervalSeconds);
        } catch (IOException ex) {
            PhotoFrameTraceLog.logIoFailure(log, "display-settings-load", path, ex);
            throw ex;
        }
    }

    public static SlideshowDisplaySettings save(Path path, SlideshowDisplaySettings settings) throws IOException {
        PhotoFrameTraceLog.tracePath(log, "display-settings-save", path);
        try {
            Path parent = path.getParent();
            if (parent != null && !Files.exists(parent)) {
                Files.createDirectories(parent);
                PhotoFrameTraceLog.logDirectoryCreated(log, parent);
            }
            SlideshowDisplaySettings normalized = settings.normalized();
            StoredSettings stored = new StoredSettings();
            stored.width = normalized.getWidth();
            stored.height = normalized.getHeight();
            stored.x = normalized.getX();
            stored.y = normalized.getY();
            stored.intervalSeconds = normalized.getIntervalSeconds();
            stored.showDisplayZone = normalized.isShowDisplayZone();
            stored.unit = normalized.getUnit();
            MAPPER.writerWithDefaultPrettyPrinter().writeValue(path.toFile(), stored);
            PhotoFrameTraceLog.logWrite(log, path, PhotoFrameTraceLog.fileSize(path));
            log.debug("IO display-settings-save OK path={}", path.toAbsolutePath());
            return normalized;
        } catch (IOException ex) {
            PhotoFrameTraceLog.logIoFailure(log, "display-settings-save", path, ex);
            throw ex;
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class StoredSettings {
        public double width = 0;
        public double height = 0;
        public double x = 0;
        public double y = 0;
        public int intervalSeconds = 0;
        public boolean showDisplayZone = false;
        public String unit = SlideshowDisplaySettings.UNIT_PIXELS;
    }
}
