#!/bin/bash
# Generated by Auto (Composer) - 2026-05-25
# Model: Composer
# Foreground run (logging to logs/backend/ like BookForge).
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

if [[ -f "$DIR/java.env" ]]; then
  # shellcheck disable=SC1091
  . "$DIR/java.env"
fi

JAVA_BIN="${JAVA_BIN:-/volume1/java/current/bin/java}"
export LOG_LEVEL="${LOG_LEVEL:-TRACE}"

if [[ ! -x "$JAVA_BIN" ]]; then
  echo "Java not found: $JAVA_BIN" >&2
  exit 1
fi

if [[ ! -f "$DIR/photoframe.jar" ]]; then
  echo "Missing photoframe.jar in $DIR" >&2
  exit 1
fi

if [[ ! -f "$DIR/google-photos-credentials.properties" ]]; then
  echo "Create google-photos-credentials.properties from the .template file, then run again." >&2
  exit 1
fi

mkdir -p "$DIR/logs/backend" "$DIR/logs/archive"

if [[ ! -f "$DIR/google-photos-picked.json" ]]; then
  cp "$DIR/google-photos-picked.json.template" "$DIR/google-photos-picked.json"
fi

exec "$JAVA_BIN" -jar "$DIR/photoframe.jar" "$@"
