#!/bin/bash
# Generated by Auto (Composer) - 2026-05-25
# Model: Composer
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

if [[ -f "$DIR/java.env" ]]; then
  # shellcheck disable=SC1091
  . "$DIR/java.env"
fi

JAVA_BIN="${JAVA_BIN:-/volume1/java/current/bin/java}"
PID_FILE="$DIR/photoframe.pid"
LOG_FILE="$DIR/photoframe.log"

if [[ ! -x "$JAVA_BIN" ]]; then
  echo "Java not found: $JAVA_BIN" >&2
  exit 1
fi

if [[ ! -f "$DIR/google-photos-credentials.properties" ]]; then
  echo "Create google-photos-credentials.properties first." >&2
  exit 1
fi

if [[ -f "$PID_FILE" ]]; then
  OLD_PID="$(cat "$PID_FILE")"
  if kill -0 "$OLD_PID" 2>/dev/null; then
    echo "PhotoFrame already running (PID $OLD_PID). Stop with ./stop.sh first." >&2
    exit 1
  fi
fi

nohup "$JAVA_BIN" -jar "$DIR/photoframe.jar" >> "$LOG_FILE" 2>&1 &
echo $! > "$PID_FILE"
echo "PhotoFrame started PID $(cat "$PID_FILE")"
echo "Log: $LOG_FILE"
