#!/bin/bash
# Generated by Auto (Composer) - 2026-05-25
# Model: Composer
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
PID_FILE="$DIR/photoframe.pid"

if [[ ! -f "$PID_FILE" ]]; then
  echo "No PID file — PhotoFrame may not be running." >&2
  exit 1
fi

PID="$(cat "$PID_FILE")"
if kill -0 "$PID" 2>/dev/null; then
  kill "$PID"
  sleep 2
  if kill -0 "$PID" 2>/dev/null; then
    kill -9 "$PID" 2>/dev/null || true
  fi
  echo "Stopped PhotoFrame (PID $PID) — see logs/backend/photoframe.log for shutdown lines"
else
  echo "Process $PID not running."
fi
rm -f "$PID_FILE"
