// Generated by Auto (Composer) - 2026-05-25
// Model: Composer
package com.mwa.photoframe.util;

import com.google.api.client.googleapis.auth.oauth2.GoogleCredential;
import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpContent;
import com.google.api.client.http.HttpRequest;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.HttpTransport;
import org.slf4j.Logger;

/**
 * Wraps Google HTTP client calls with timing and trace logging.
 */
public final class GoogleHttpTrace {

    private GoogleHttpTrace() {
    }

    public static HttpResponse executeGet(
            Logger log, String label, HttpTransport transport, GoogleCredential credential, GenericUrl url)
            throws Exception {
        PhotoFrameTraceLog.logGoogleApi(log, label, "GET " + PhotoFrameTraceLog.sanitizeUrl(url.toString()));
        return execute(log, label, "GET", transport, credential, url, null);
    }

    public static HttpResponse executePost(
            Logger log,
            String label,
            HttpTransport transport,
            GoogleCredential credential,
            GenericUrl url,
            HttpContent content)
            throws Exception {
        PhotoFrameTraceLog.logGoogleApi(log, label, "POST " + PhotoFrameTraceLog.sanitizeUrl(url.toString()));
        return execute(log, label, "POST", transport, credential, url, content);
    }

    public static HttpResponse executeDelete(
            Logger log, String label, HttpTransport transport, GoogleCredential credential, GenericUrl url)
            throws Exception {
        PhotoFrameTraceLog.logGoogleApi(log, label, "DELETE " + PhotoFrameTraceLog.sanitizeUrl(url.toString()));
        return execute(log, label, "DELETE", transport, credential, url, null);
    }

    private static HttpResponse execute(
            Logger log,
            String label,
            String method,
            HttpTransport transport,
            GoogleCredential credential,
            GenericUrl url,
            HttpContent content)
            throws Exception {
        String urlStr = url.toString();
        long start = System.currentTimeMillis();
        PhotoFrameTraceLog.logHttpStart(log, method, urlStr);
        try {
            HttpRequest request;
            if ("POST".equals(method)) {
                request = transport.createRequestFactory(credential).buildPostRequest(url, content);
            } else if ("DELETE".equals(method)) {
                request = transport.createRequestFactory(credential).buildDeleteRequest(url);
            } else {
                request = transport.createRequestFactory(credential).buildGetRequest(url);
            }
            HttpResponse response = request.execute();
            long elapsed = System.currentTimeMillis() - start;
            int status = response.getStatusCode();
            PhotoFrameTraceLog.logHttpSuccess(log, method, urlStr, status, elapsed, -1);
            return response;
        } catch (Exception ex) {
            long elapsed = System.currentTimeMillis() - start;
            PhotoFrameTraceLog.logHttpFailure(log, method, urlStr, elapsed, ex);
            PhotoFrameTraceLog.logGoogleApiError(log, method + " " + label, ex);
            throw ex;
        }
    }
}
