// Generated by Auto (Composer) - 2026-05-30
// Model: Composer
package com.mwa.photoframe.util;

import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Resolves project-relative paths for local dev ({@code backend/} cwd) and containers ({@code PHOTOFRAME_HOME}).
 */
public final class PhotoFramePaths {

    private PhotoFramePaths() {
    }

    public static Path projectRoot() {
        String home = System.getenv("PHOTOFRAME_HOME");
        if (home != null && !home.isBlank()) {
            return Paths.get(home.trim()).toAbsolutePath().normalize();
        }
        Path cwd = Paths.get(System.getProperty("user.dir", ".")).toAbsolutePath().normalize();
        if (cwd.getFileName() != null && "backend".equals(cwd.getFileName().toString())) {
            Path parent = cwd.getParent();
            if (parent != null) {
                return parent;
            }
        }
        return cwd;
    }

    public static Path resolve(String configuredPath) {
        if (configuredPath == null || configuredPath.isBlank()) {
            return projectRoot();
        }
        Path path = Paths.get(configuredPath.trim());
        if (path.isAbsolute()) {
            return path.normalize();
        }
        return projectRoot().resolve(path).normalize();
    }
}
