// Generated by Auto (Composer) - 2026-05-25
// Model: Composer
package com.mwa.photoframe.util;

import org.slf4j.Logger;

import java.io.File;
import java.io.IOException;
import java.nio.file.AccessDeniedException;
import java.nio.file.FileStore;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;

/**
 * Central trace/debug helpers for file I/O and error classification (disk full, permissions, etc.).
 */
public final class PhotoFrameTraceLog {

    private PhotoFrameTraceLog() {
    }

    public static void tracePath(Logger log, String operation, Path path) {
        if (!log.isTraceEnabled()) {
            return;
        }
        Path abs = path != null ? path.toAbsolutePath().normalize() : null;
        log.trace("IO {} path={} exists={} readable={} writable={}",
                operation,
                abs,
                path != null && Files.exists(path),
                path != null && Files.isReadable(path),
                path != null && Files.isWritable(path));
        if (abs != null && abs.getParent() != null) {
            logFreeSpace(log, "trace", abs.getParent());
        }
    }

    public static void debugPath(Logger log, String operation, Path path) {
        Path abs = path != null ? path.toAbsolutePath().normalize() : null;
        log.debug("IO {} path={} size={} bytes", operation, abs, fileSize(path));
    }

    public static void logRead(Logger log, Path path, long bytes) {
        log.debug("IO read OK path={} bytes={}", path.toAbsolutePath(), bytes);
    }

    public static void logWrite(Logger log, Path path, long bytes) {
        log.debug("IO write OK path={} bytes={}", path.toAbsolutePath(), bytes);
        logFreeSpace(log, "after-write", path.getParent());
    }

    public static void logDirectoryCreated(Logger log, Path dir) {
        log.debug("IO mkdir path={}", dir.toAbsolutePath());
        logFreeSpace(log, "after-mkdir", dir);
    }

    public static void logIoFailure(Logger log, String operation, Path path, Exception ex) {
        Path abs = path != null ? path.toAbsolutePath().normalize() : null;
        log.error("IO {} FAILED path={} reason={} message={}",
                operation, abs, classifyIo(ex), ex.getMessage(), ex);
        if (abs != null && abs.getParent() != null) {
            logFreeSpace(log, "on-io-failure", abs.getParent());
        }
    }

    public static String classifyIo(Throwable ex) {
        if (ex == null) {
            return "unknown";
        }
        if (ex instanceof AccessDeniedException) {
            return "access-denied";
        }
        if (ex instanceof NoSuchFileException) {
            return "not-found";
        }
        String msg = ex.getMessage();
        if (msg == null) {
            msg = "";
        }
        String lower = msg.toLowerCase();
        if (lower.contains("no space left") || lower.contains("disk full") || lower.contains("enospc")) {
            return "disk-full";
        }
        if (lower.contains("permission denied") || lower.contains("access denied")) {
            return "access-denied";
        }
        if (lower.contains("read-only file system") || lower.contains("erofs")) {
            return "read-only-filesystem";
        }
        if (lower.contains("too many open files")) {
            return "too-many-open-files";
        }
        if (ex instanceof IOException) {
            return "io-error";
        }
        return ex.getClass().getSimpleName();
    }

    public static void logFreeSpace(Logger log, String context, Path dir) {
        if (!log.isDebugEnabled() || dir == null) {
            return;
        }
        try {
            Path target = Files.isDirectory(dir) ? dir : dir.getParent();
            if (target == null) {
                return;
            }
            FileStore store = Files.getFileStore(target);
            long usable = store.getUsableSpace();
            long total = store.getTotalSpace();
            log.debug("Disk [{}] path={} usable={} MB total={} MB",
                    context,
                    target.toAbsolutePath(),
                    usable / (1024 * 1024),
                    total > 0 ? total / (1024 * 1024) : -1);
        } catch (IOException ex) {
            log.trace("Disk space check skipped [{}] dir={}: {}", context, dir, ex.getMessage());
        }
    }

    public static long fileSize(Path path) {
        if (path == null) {
            return -1;
        }
        try {
            if (Files.isRegularFile(path)) {
                return Files.size(path);
            }
        } catch (IOException ignored) {
            return -1;
        }
        return -1;
    }

    public static void logHttpStart(Logger log, String method, String url) {
        log.debug("HTTP {} START url={}", method, sanitizeUrl(url));
    }

    public static void logHttpSuccess(Logger log, String method, String url, int status, long elapsedMs, long bytes) {
        log.debug("HTTP {} OK status={} elapsedMs={} bytes={} url={}",
                method, status, elapsedMs, bytes, sanitizeUrl(url));
    }

    public static void logHttpFailure(Logger log, String method, String url, long elapsedMs, Throwable ex) {
        int status = -1;
        String detail = ex.getMessage();
        if (ex instanceof com.google.api.client.http.HttpResponseException) {
            status = ((com.google.api.client.http.HttpResponseException) ex).getStatusCode();
        }
        log.error("HTTP {} FAILED status={} elapsedMs={} reason={} url={} message={}",
                method, status, elapsedMs, classifyNetwork(ex), sanitizeUrl(url), detail, ex);
    }

    public static String classifyNetwork(Throwable ex) {
        if (ex == null) {
            return "unknown";
        }
        if (ex instanceof java.net.SocketTimeoutException) {
            return "timeout";
        }
        if (ex instanceof java.net.ConnectException) {
            return "connection-refused";
        }
        if (ex instanceof java.net.UnknownHostException) {
            return "unknown-host";
        }
        if (ex instanceof javax.net.ssl.SSLException) {
            return "ssl-error";
        }
        if (ex instanceof com.google.api.client.http.HttpResponseException) {
            return "http-" + ((com.google.api.client.http.HttpResponseException) ex).getStatusCode();
        }
        return ex.getClass().getSimpleName();
    }

    public static String sanitizeUrl(String url) {
        if (url == null) {
            return "";
        }
        int q = url.indexOf('?');
        if (q > 0) {
            return url.substring(0, q) + "?…";
        }
        if (url.length() > 120) {
            return url.substring(0, 120) + "…";
        }
        return url;
    }

    public static void logGoogleApi(Logger log, String api, String detail) {
        log.debug("GooglePhotos API {} {}", api, detail);
    }

    public static void logGoogleApiError(Logger log, String api, Throwable ex) {
        log.error("GooglePhotos API {} FAILED reason={} message={}",
                api, classifyNetwork(ex), ex.getMessage(), ex);
    }

    public static void logApiRequest(Logger log, String method, String uri, int status, long elapsedMs) {
        log.debug("REST {} {} status={} elapsedMs={}", method, uri, status, elapsedMs);
    }
}
