// Generated by Auto (Composer) - 2026-05-30
// Model: Composer
package com.mwa.photoframe.storage;

/**
 * Logical storage keys for PhotoFrame blobs (provider-agnostic paths).
 */
public final class PhotoFrameStorageKeys {

    private PhotoFrameStorageKeys() {
    }

    public static String googlePhotoJpeg(String keyPrefix, String mediaId) {
        String prefix = normalizePrefix(keyPrefix);
        return prefix + "/" + safeSegment(mediaId) + ".jpg";
    }

    private static String normalizePrefix(String prefix) {
        if (prefix == null || prefix.isBlank()) {
            return "google-photos-cache";
        }
        String p = prefix.trim().replace('\\', '/');
        while (p.startsWith("/")) {
            p = p.substring(1);
        }
        while (p.endsWith("/")) {
            p = p.substring(0, p.length() - 1);
        }
        return p.isEmpty() ? "google-photos-cache" : p;
    }

    private static String safeSegment(String mediaId) {
        return mediaId.replaceAll("[^a-zA-Z0-9._-]", "_");
    }
}
