#!/usr/bin/env bash
# Generated by Auto (Composer) - 2026-05-24
# Model: Composer
# Build photoframe.jar and pack a deployable tar.gz (extract, configure, ./run.sh).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="1.0.0"
DIST="$ROOT/dist"
STAGE="$DIST/photoframe"
ARCHIVE="$DIST/photoframe-deploy-${VERSION}.tar.gz"

rm -rf "$DIST"
mkdir -p "$STAGE/images" "$STAGE/google-photos-cache"

echo "Building JAR..."
"$ROOT/scripts/package.sh"

cp "$ROOT/backend/target/photoframe.jar" "$STAGE/photoframe.jar"
cp "$ROOT/deploy/run.sh" "$STAGE/run.sh"
cp "$ROOT/deploy/start-background.sh" "$STAGE/start-background.sh"
cp "$ROOT/deploy/stop.sh" "$STAGE/stop.sh"
cp "$ROOT/deploy/java.env" "$STAGE/java.env"
cp "$ROOT/deploy/README-DEPLOY.txt" "$STAGE/README-DEPLOY.txt"
cp "$ROOT/google-photos-credentials.properties.template" "$STAGE/"
cp "$ROOT/google-photos-picked.json.template" "$STAGE/google-photos-picked.json.template"
cp "$ROOT/deploy/slideshow-display.json.template" "$STAGE/"
cp "$ROOT/google-photos-picked.json.template" "$STAGE/google-photos-picked.json"

chmod +x "$STAGE/run.sh" "$STAGE/start-background.sh" "$STAGE/stop.sh"
touch "$STAGE/images/.keep" "$STAGE/google-photos-cache/.keep"

echo "Creating archive..."
tar -czf "$ARCHIVE" -C "$DIST" photoframe

echo ""
echo "Deploy package: $ARCHIVE"
ls -lh "$ARCHIVE"
echo ""
echo "Install:"
echo "  tar xzf $(basename "$ARCHIVE") -C /path/to/install"
echo "  cd /path/to/install/photoframe"
echo "  cp google-photos-credentials.properties.template google-photos-credentials.properties"
echo "  # edit credentials"
echo "  ./start-background.sh"
