#!/usr/bin/env bash
# Generated by Auto (Composer) - 2026-05-24
# Model: Composer
# Build photoframe.jar and pack a deployable tar.gz (extract, configure, ./run.sh).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="1.0.0"
DIST="$ROOT/dist"
STAGE="$DIST/photoframe"
ARCHIVE="$DIST/photoframe-deploy-${VERSION}.tar.gz"

rm -rf "$DIST"
mkdir -p "$STAGE/images" "$STAGE/google-photos-cache" "$STAGE/logs/backend" "$STAGE/logs/archive"

echo "Building JAR..."
"$ROOT/scripts/package.sh"

cp "$ROOT/backend/target/photoframe.jar" "$STAGE/photoframe.jar"
cp "$ROOT/deploy/run.sh" "$STAGE/run.sh"
cp "$ROOT/deploy/start-background.sh" "$STAGE/start-background.sh"
cp "$ROOT/deploy/stop.sh" "$STAGE/stop.sh"
cp "$ROOT/deploy/java.env" "$STAGE/java.env"
cp "$ROOT/deploy/README-DEPLOY.txt" "$STAGE/README-DEPLOY.txt"
cp -R "$ROOT/deploy/logs/README.md" "$STAGE/logs/"
cp "$ROOT/google-photos-credentials.properties.template" "$STAGE/"
cp "$ROOT/google-photos-picked.json.template" "$STAGE/google-photos-picked.json.template"
cp "$ROOT/deploy/slideshow-display.json.template" "$STAGE/"
cp "$ROOT/google-photos-picked.json.template" "$STAGE/google-photos-picked.json"

chmod +x "$STAGE/run.sh" "$STAGE/start-background.sh" "$STAGE/stop.sh"
touch "$STAGE/images/.keep" "$STAGE/google-photos-cache/.keep" "$STAGE/logs/backend/.keep"

echo "Creating archive..."
tar -czf "$ARCHIVE" -C "$DIST" photoframe

echo ""
echo "Deploy package: $ARCHIVE"
ls -lh "$ARCHIVE"
echo ""
echo "Install (extract into PARENT of install dir, e.g. /volume1/apps):"
echo "  cd /volume1/apps"
echo "  tar xzf $(basename "$ARCHIVE")"
echo "  cd photoframe"
echo "  ls start-background.sh stop.sh run.sh"
echo "  cp google-photos-credentials.properties.template google-photos-credentials.properties"
echo "  ./start-background.sh"
echo ""
echo "If scripts are missing, you may have extracted inside photoframe/ — check:"
echo "  ls photoframe/photoframe/start-background.sh"
