#!/usr/bin/env bash
# Generated by Auto (Composer) - 2026-05-25
# Model: Composer
# PhotoFrame log helper (BookForge-style paths).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOG_BACKEND="$ROOT/logs/backend"

cmd="${1:-status}"

case "$cmd" in
  status)
    echo "Log directory: $LOG_BACKEND"
    if [[ -d "$LOG_BACKEND" ]]; then
      ls -lh "$LOG_BACKEND" 2>/dev/null || true
    else
      echo "(not created yet — start PhotoFrame once)"
    fi
    ;;
  tail)
    tail -f "$LOG_BACKEND/photoframe.log"
    ;;
  errors)
    tail -100 "$LOG_BACKEND/error.log" 2>/dev/null || echo "No error.log yet"
    ;;
  why-stopped)
    echo "=== Recent errors (photoframe.log) ==="
    grep -E "ERROR|FATAL|shutdown|Exception|OutOfMemory" "$LOG_BACKEND/photoframe.log" 2>/dev/null | tail -40 || true
    echo ""
    echo "=== error.log ==="
    tail -30 "$LOG_BACKEND/error.log" 2>/dev/null || true
    ;;
  *)
    echo "Usage: $0 {status|tail|errors|why-stopped}"
    exit 1
    ;;
esac
