#!/usr/bin/env bash
# Generated by Auto (Composer) - 2026-05-24
# Model: Composer
# Build executable PhotoFrame JAR (Java 21, Spring Boot 3 — main branch).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT/backend"
mvn -q clean package -DskipTests
JAR="$ROOT/backend/target/photoframe.jar"
if [[ ! -f "$JAR" ]]; then
  echo "Build failed: $JAR not found" >&2
  exit 1
fi
echo "Built: $JAR"
ls -lh "$JAR"
