#!/usr/bin/env bash
# Generated by Auto (Composer) - 2026-05-24
# Model: Composer
# Run PhotoFrame from the packaged JAR. Run from photoframe/ so ./ config files resolve.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JAR="$ROOT/backend/target/photoframe.jar"
if [[ ! -f "$JAR" ]]; then
  echo "JAR not found. Run: ./scripts/package.sh" >&2
  exit 1
fi
cd "$ROOT"
export LOG_LEVEL="${LOG_LEVEL:-TRACE}"
exec java -jar "$JAR" "$@"
