// Generated by Auto (Composer) - 2026-05-25
// Model: Composer
package com.mwa.photoframe.config;

import com.mwa.photoframe.util.PhotoFrameTraceLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * Logs every incoming HTTP API request (method, URI, status, duration).
 */
@Component
@Order(Ordered.HIGHEST_PRECEDENCE + 20)
public class PhotoFrameApiLoggingFilter extends OncePerRequestFilter {

    private static final Logger log = LoggerFactory.getLogger("com.mwa.photoframe.api.request");

    @Override
    protected void doFilterInternal(
            HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
            throws ServletException, IOException {
        String uri = request.getRequestURI();
        if (uri == null || !uri.startsWith("/api/")) {
            filterChain.doFilter(request, response);
            return;
        }
        String method = request.getMethod();
        long start = System.currentTimeMillis();
        if (log.isTraceEnabled()) {
            log.trace("REST {} {} query={} remote={}",
                    method, uri, request.getQueryString(), request.getRemoteAddr());
        }
        try {
            filterChain.doFilter(request, response);
        } finally {
            long elapsed = System.currentTimeMillis() - start;
            PhotoFrameTraceLog.logApiRequest(log, method, uri, response.getStatus(), elapsed);
        }
    }
}
