// Generated by Auto (Composer) - 2026-05-21
package com.mwa.photoframe.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;

@Configuration
public class PhotoFrameConfig {

    @Value("${photoframe.source:local}")
    private String defaultSource;

    @Value("${photoframe.local.folder:./images}")
    private String localFolder;

    @Value("${photoframe.timer.seconds.default:5}")
    private int defaultTimerSeconds;

    @Value("${photoframe.google.credentials.path:./google-photos-credentials.properties}")
    private String googleCredentialsPath;

    @Value("${photoframe.google.picked.file:./google-photos-picked.json}")
    private String googlePickedFile;

    @Value("${photoframe.google.cache.dir:./google-photos-cache}")
    private String googleCacheDir;

    /** Logical key prefix for Google JPEG blobs inside {@link com.photoframe.storage.StorageService}. */
    @Value("${photoframe.storage.google.key-prefix:google-photos-cache}")
    private String storageGoogleKeyPrefix;

    @Value("${photoframe.display.settings.file:./slideshow-display.json}")
    private String displaySettingsFile;

    public String getDefaultSource() {
        return defaultSource;
    }

    public String getLocalFolder() {
        return localFolder;
    }

    public int getDefaultTimerSeconds() {
        return defaultTimerSeconds;
    }

    public String getGoogleCredentialsPath() {
        return googleCredentialsPath;
    }

    public String getGooglePickedFile() {
        return googlePickedFile;
    }

    public String getGoogleCacheDir() {
        return googleCacheDir;
    }

    public String getStorageGoogleKeyPrefix() {
        return storageGoogleKeyPrefix;
    }

    public String getDisplaySettingsFile() {
        return displaySettingsFile;
    }
}
