// Generated by Auto (Composer) - 2026-05-30
// Model: Composer
package com.mwa.photoframe.config;

import com.azure.storage.blob.BlobContainerClient;
import com.azure.storage.blob.BlobServiceClient;
import com.azure.storage.blob.BlobServiceClientBuilder;
import com.photoframe.storage.StorageAccessException;
import com.photoframe.storage.StorageService;
import com.photoframe.storage.azure.AzureBlobStorageService;
import com.photoframe.storage.filesystem.FileSystemStorageService;
import com.photoframe.storage.spring.StorageProperties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.mwa.photoframe.util.PhotoFramePaths;

import java.nio.file.Path;

/**
 * Wires {@link StorageService} for PhotoFrame (filesystem or Azure), resolving paths like other config.
 */
@Configuration
@EnableConfigurationProperties(StorageProperties.class)
public class PhotoFrameStorageConfiguration {

    private static final Logger log = LoggerFactory.getLogger(PhotoFrameStorageConfiguration.class);

    @Bean
    @ConditionalOnMissingBean(StorageService.class)
    public StorageService storageService(StorageProperties storageProperties) {
        String provider = storageProperties.getProvider() != null
                ? storageProperties.getProvider().trim().toLowerCase()
                : "filesystem";
        if ("azure".equals(provider)) {
            StorageService azure = createAzureStorage(storageProperties);
            log.info("PhotoFrame storage: Azure Blob container={}",
                    storageProperties.getAzure().getContainerName());
            return azure;
        }
        Path root = resolveRootPath(storageProperties.getFilesystem().getRootDirectory());
        log.info("PhotoFrame storage: filesystem root={}", root);
        return new FileSystemStorageService(root);
    }

    private static StorageService createAzureStorage(StorageProperties properties) {
        String connectionString = properties.getAzure().getConnectionString();
        if (connectionString == null || connectionString.isBlank()) {
            throw new StorageAccessException("storage.azure.connection-string must be set when storage.provider=azure");
        }
        String containerName = properties.getAzure().getContainerName();
        if (containerName == null || containerName.isBlank()) {
            throw new StorageAccessException("storage.azure.container-name must be set");
        }
        BlobServiceClient serviceClient = new BlobServiceClientBuilder()
                .connectionString(connectionString)
                .buildClient();
        BlobContainerClient containerClient = serviceClient.getBlobContainerClient(containerName);
        if (!containerClient.exists()) {
            containerClient.create();
        }
        return new AzureBlobStorageService(containerClient);
    }

    public static Path resolveRootPath(String configured) {
        return PhotoFramePaths.resolve(configured != null && !configured.isBlank() ? configured.trim() : ".");
    }
}
