// Generated by Auto (Composer) - 2026-05-21
package com.mwa.photoframe.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.ViewControllerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@Configuration
public class WebConfig implements WebMvcConfigurer {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/**")
                .addResourceLocations("file:../frontend/");
    }

    @Override
    public void addViewControllers(ViewControllerRegistry registry) {
        // Forward (not redirect) so ?interval= and other query params are preserved.
        registry.addViewController("/").setViewName("forward:/index.html");
        registry.addViewController("/myphotoframe").setViewName("forward:/myphotoframe.html");
        registry.addViewController("/pick").setViewName("forward:/myphotoframe.html");
        registry.addViewController("/pick.html").setViewName("forward:/myphotoframe.html");
    }
}
