// Generated by Auto (Composer) - 2026-05-24
// Model: Composer
package com.mwa.photoframe.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.ViewControllerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

@Configuration
public class WebConfig implements WebMvcConfigurer {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        String location = resolveFrontendLocation();
        registry.addResourceHandler("/**")
                .addResourceLocations(location);
    }

    /**
     * Dev: serve from {@code ../frontend} or {@code ./frontend} when present.
     * Deployed JAR: serve HTML/JS bundled under {@code classpath:/static/}.
     */
    static String resolveFrontendLocation() {
        Path sibling = Paths.get("frontend").toAbsolutePath().normalize();
        if (Files.isDirectory(sibling)) {
            return pathToFileUrl(sibling);
        }
        Path parent = Paths.get("..", "frontend").toAbsolutePath().normalize();
        if (Files.isDirectory(parent)) {
            return pathToFileUrl(parent);
        }
        return "classpath:/static/";
    }

    private static String pathToFileUrl(Path dir) {
        String uri = dir.toUri().toString();
        if (!uri.endsWith("/")) {
            uri = uri + "/";
        }
        return uri;
    }

    @Override
    public void addViewControllers(ViewControllerRegistry registry) {
        // Forward (not redirect) so ?interval= and other query params are preserved.
        registry.addViewController("/").setViewName("forward:/index.html");
        registry.addViewController("/myphotoframe").setViewName("forward:/myphotoframe.html");
        registry.addViewController("/pick").setViewName("forward:/myphotoframe.html");
        registry.addViewController("/pick.html").setViewName("forward:/myphotoframe.html");
    }
}
