// Generated by Auto (Composer) - 2026-05-25
// Model: Composer
package com.mwa.photoframe;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication
public class PhotoFrameApplication {

    private static final Logger log = LoggerFactory.getLogger(PhotoFrameApplication.class);

    public static void main(String[] args) {
        log.info("Starting PhotoFrame (Java {})", System.getProperty("java.version"));
        log.info("Working directory: {}", System.getProperty("user.dir"));
        Runtime.getRuntime().addShutdownHook(new Thread(() -> log.warn(
                "PhotoFrame JVM shutdown hook — process ended (see logs/backend/error.log if unexpected)")));

        ConfigurableApplicationContext context =
                SpringApplication.run(PhotoFrameApplication.class, args);
        String port = context.getEnvironment().getProperty("server.port", "8082");
        log.info("PhotoFrame ready — http://0.0.0.0:{}/", port);
        log.info("Logs: logs/backend/photoframe.log (and error.log, api.log, debug.log)");
    }
}
